/*
Some of this code began its life as a part of GTA V SCRIPT HOOK SDK.
http://dev-c.com
(C) Alexander Blade 2015

It is now part of the Enhanced Native Trainer project.
https://github.com/gtav-ent/GTAV-EnhancedNativeTrainer
(C) Sondai SMith and fellow contributors 2015
*/

#pragma once

#include "..\..\inc\natives.h"
#include "..\..\inc\types.h"
#include "..\..\inc\enums.h"
#include "..\..\inc\main.h"

#include "..\ui_support\menu_functions.h"

#include "..\storage\database.h"

const std::vector<std::string> MENU_WEAPON_CATEGORIES{"Melee", "Handguns", "Submachine Guns", "Assault Rifles", "Shotguns", "Sniper Rifles", "Heavy Weapons", "Thrown Weapons"};

// Count: 19
const std::vector<std::string> CAPTIONS_MELEE{ "Knife", "Nightstick", "Hammer", "Baseball Bat", "Chop's Ball", "Digiscanner", "Golf Club", "Crowbar", "Bottle", "Antique Dagger", "Hatchet", "Knuckle Duster", "Machete", "Flashlight", "Switchblade", "Battleaxe", "Pipe Wrench", "Poolcue", "Stone Hatchet" };
const std::vector<std::string> VALUES_MELEE{ "WEAPON_KNIFE", "WEAPON_NIGHTSTICK", "WEAPON_HAMMER", "WEAPON_BAT", "WEAPON_BALL", "WEAPON_DIGISCANNER", "WEAPON_GOLFCLUB", "WEAPON_CROWBAR", "WEAPON_BOTTLE", "WEAPON_DAGGER", "WEAPON_HATCHET", "WEAPON_KNUCKLE", "WEAPON_MACHETE", "WEAPON_FLASHLIGHT", "WEAPON_SWITCHBLADE", "WEAPON_BATTLEAXE", "WEAPON_WRENCH", "WEAPON_POOLCUE", "WEAPON_STONE_HATCHET" };
// Count: 15
const std::vector<std::string> CAPTIONS_HANDGUN{ "Pistol", "Pistol MK2", "Combat Pistol", "AP Pistol", "Pistol .50", "SNS Pistol", "SNS Pistol MK2", "Heavy Pistol", "Vintage Pistol", "Stun Gun", "Flare Gun", "Marksman Pistol", "Revolver", "Revolver MK2", "Double Action Revolver" };
const std::vector<std::string> VALUES_HANDGUN{ "WEAPON_PISTOL", "WEAPON_PISTOL_MK2", "WEAPON_COMBATPISTOL", "WEAPON_APPISTOL", "WEAPON_PISTOL50", "WEAPON_SNSPISTOL", "WEAPON_SNSPISTOL_MK2", "WEAPON_HEAVYPISTOL", "WEAPON_VINTAGEPISTOL", "WEAPON_STUNGUN", "WEAPON_FLAREGUN", "WEAPON_MARKSMANPISTOL", "WEAPON_REVOLVER", "WEAPON_REVOLVER_MK2", "WEAPON_DOUBLEACTION" };
// Count: 10
const std::vector<std::string> CAPTIONS_SUBMACHINE{ "Micro SMG", "SMG", "SMG MK2", "Assault SMG", "MG", "Combat MG", "Combat MG MK2", "Gusenberg Sweeper", "Combat PDW", "Machine Pistol", "Mini SMG", };
const std::vector<std::string> VALUES_SUBMACHINE{ "WEAPON_MICROSMG", "WEAPON_SMG", "WEAPON_SMG_MK2", "WEAPON_ASSAULTSMG", "WEAPON_MG", "WEAPON_COMBATMG", "WEAPON_COMBATMG_MK2", "WEAPON_GUSENBERG", "WEAPON_COMBATPDW", "WEAPON_MACHINEPISTOL", "WEAPON_MINISMG" };
// Count: 8
const std::vector<std::string> CAPTIONS_ASSAULT{ "Assault Rifle", "Assault Rifle MK2", "Bullpup Rifle MK2", "Carbine Rifle", "Carbine Rifle MK2", "Advanced Rifle", "Special Carbine", "Special Carbine MK2", "Bullpup Rifle", "Compact Rifle",  };
const std::vector<std::string> VALUES_ASSAULT{ "WEAPON_ASSAULTRIFLE", "WEAPON_ASSAULTRIFLE_MK2", "WEAPON_BULLPUPRIFLE_MK2", "WEAPON_CARBINERIFLE", "WEAPON_CARBINERIFLE_MK2", "WEAPON_ADVANCEDRIFLE", "WEAPON_SPECIALCARBINE", "WEAPON_SPECIALCARBINE_MK2", "WEAPON_BULLPUPRIFLE", "WEAPON_COMPACTRIFLE" };
// Count: 9
const std::vector<std::string> CAPTIONS_SHOTGUN{ "Pump Shotgun", "Pump Shotgun MK2", "Sawed-Off Shotgun", "Bullpup Shotgun", "Assault Shotgun", "Musket", "Heavy Shotgun", "Double Barrel Shotgun", "Sweeper Shotgun",  };
const std::vector<std::string> VALUES_SHOTGUN{ "WEAPON_PUMPSHOTGUN", "WEAPON_PUMPSHOTGUN_MK2", "WEAPON_SAWNOFFSHOTGUN", "WEAPON_BULLPUPSHOTGUN", "WEAPON_ASSAULTSHOTGUN", "WEAPON_MUSKET", "WEAPON_HEAVYSHOTGUN", "WEAPON_DBSHOTGUN", "WEAPON_AUTOSHOTGUN",  };
// Count: 3
const std::vector<std::string> CAPTIONS_SNIPER{ "Sniper Rifle", "Heavy Sniper", "Heavy Sniper MK2", "Marksman Rifle", "Marksman Rifle MK2",  };
const std::vector<std::string> VALUES_SNIPER{ "WEAPON_SNIPERRIFLE", "WEAPON_HEAVYSNIPER", "WEAPON_HEAVYSNIPER_MK2", "WEAPON_MARKSMANRIFLE", "WEAPON_MARKSMANRIFLE_MK2",  };
// Count: 7
const std::vector<std::string> CAPTIONS_HEAVY{ "Grenade Launcher", "RPG", "Minigun", "Fireworks Launcher", "Railgun", "Homing Launcher", "Compact Grenade Launcher" };
const std::vector<std::string> VALUES_HEAVY{ "WEAPON_GRENADELAUNCHER", "WEAPON_RPG", "WEAPON_MINIGUN", "WEAPON_FIREWORK", "WEAPON_RAILGUN", "WEAPON_HOMINGLAUNCHER", "WEAPON_COMPACTLAUNCHER" };
// Count: 10
const std::vector<std::string> CAPTIONS_THROWN{ "Grenade", "Sticky Bomb", "Proximity Mine", "Teargas", "Molotov", "Fire Extinguisher", "Jerry Can", "Snowball", "Flare", "Pipebomb" };
const std::vector<std::string> VALUES_THROWN{ "WEAPON_GRENADE", "WEAPON_STICKYBOMB", "WEAPON_PROXMINE", "WEAPON_SMOKEGRENADE", "WEAPON_MOLOTOV", "WEAPON_FIREEXTINGUISHER", "WEAPON_PETROLCAN", "WEAPON_SNOWBALL", "WEAPON_FLARE", "WEAPON_PIPEBOMB" };


const std::vector<std::string> VOV_WEAPON_CAPTIONS[] = {CAPTIONS_MELEE, CAPTIONS_HANDGUN, CAPTIONS_SUBMACHINE, CAPTIONS_ASSAULT, CAPTIONS_SHOTGUN, CAPTIONS_SNIPER, CAPTIONS_HEAVY, CAPTIONS_THROWN};
const std::vector<std::string> VOV_WEAPON_VALUES[] = {VALUES_MELEE, VALUES_HANDGUN, VALUES_SUBMACHINE, VALUES_ASSAULT, VALUES_SHOTGUN, VALUES_SNIPER, VALUES_HEAVY, VALUES_THROWN};

//Weapon tints
const std::vector<std::string> CAPTIONS_TINT{"Normal", "Green", "Gold", "Pink", "Army", "LSPD", "Orange", "Platinum"};
const std::vector<int> VALUES_TINT{0, 1, 2, 3, 4, 5, 6, 7};

//Weapon tints for MK2 weapons
const std::vector<std::string> CAPTIONS_TINT_MK2{ "Classic Black", "Classic Gray", "Classic Two-Tone", "Classic White", "Classic Beige", "Classic Green", "Classic Blue", "Classic Earth", "Classic Brown & Black", "Red Contrast", "Blue Contrast", "Yellow Contrast", "Orange Contrast", "Bold Pink", "Bold Purple & Yellow", "Bold Orange", "Bold Green & Purple", "Bold Red Features", "Bold Green Features", "Bold Cyan Features", "Bold Yellow Features", "Bold Red & White", "Bold Blue & White", "Metallic Gold", "Metallic Platinum", "Metallic Gray & Lilca", "Metallic Purple & Lime", "Metallic Red", "Metallic Green", "Metallic Blue", "Metallic White & Aqua", "Metallic Red & Yellow" };
const std::vector<int> VALUES_TINT_MK2{ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31 };

//Pistols
const std::vector<std::string> CAPTIONS_ATTACH_PISTOL{"Extended Magazine", "Flashlight", "Suppressor", "Yusuf Amir Luxury Finish"};
const std::vector<std::string> VALUES_ATTACH_PISTOL{"COMPONENT_PISTOL_CLIP_02", "COMPONENT_AT_PI_FLSH", "COMPONENT_AT_PI_SUPP_02", "COMPONENT_PISTOL_VARMOD_LUXE"};

const std::vector<std::string> CAPTIONS_ATTACH_COMBATPISTOL{"Extended Magazine", "Flashlight", "Suppressor", "Yusuf Amir Luxury Finish"};
const std::vector<std::string> VALUES_ATTACH_COMBATPISTOL{"COMPONENT_COMBATPISTOL_CLIP_02", "COMPONENT_AT_PI_FLSH", "COMPONENT_AT_PI_SUPP", "COMPONENT_COMBATPISTOL_VARMOD_LOWRIDER"};

const std::vector<std::string> CAPTIONS_ATTACH_APPISTOL{"Extended Magazine", "Flashlight", "Suppressor", "Gilded Gun Metal Finish"};
const std::vector<std::string> VALUES_ATTACH_APPISTOL{"COMPONENT_APPISTOL_CLIP_02", "COMPONENT_AT_PI_FLSH", "COMPONENT_AT_PI_SUPP", "COMPONENT_APPISTOL_VARMOD_LUXE"};

const std::vector<std::string> CAPTIONS_ATTACH_PISTOL50{"Extended Magazine", "Flashlight", "Suppressor", "Platinum Pearl Deluxe Finish"};
const std::vector<std::string> VALUES_ATTACH_PISTOL50{"COMPONENT_PISTOL50_CLIP_02", "COMPONENT_AT_PI_FLSH", "COMPONENT_AT_AR_SUPP_02", "COMPONENT_PISTOL50_VARMOD_LUXE"};

//SMGs
const std::vector<std::string> CAPTIONS_ATTACH_MICROSMG{"Extended Magazine", "Flashlight", "Scope", "Suppressor", "Yusuf Amir Luxury Finish"};
const std::vector<std::string> VALUES_ATTACH_MICROSMG{"COMPONENT_MICROSMG_CLIP_02", "COMPONENT_AT_PI_FLSH", "COMPONENT_AT_SCOPE_MACRO", "COMPONENT_AT_AR_SUPP_02", "COMPONENT_MICROSMG_VARMOD_LUXE"};

const std::vector<std::string> CAPTIONS_ATTACH_SMG{"Extended Magazine", "Drum Magazine", "Flashlight", "Scope", "Suppressor", "Yusuf Amir Luxury Finish"};
const std::vector<std::string> VALUES_ATTACH_SMG{"COMPONENT_SMG_CLIP_02", "COMPONENT_SMG_CLIP_03", "COMPONENT_AT_AR_FLSH", "COMPONENT_AT_SCOPE_MACRO_02", "COMPONENT_AT_PI_SUPP", "COMPONENT_SMG_VARMOD_LUXE"};

const std::vector<std::string> CAPTIONS_ATTACH_ASSAULTSMG{"Extended Magazine", "Flashlight", "Scope", "Suppressor", "Yusuf Amir Luxury Finish"};
const std::vector<std::string> VALUES_ATTACH_ASSAULTSMG{"COMPONENT_ASSAULTSMG_CLIP_02", "COMPONENT_AT_AR_FLSH", "COMPONENT_AT_SCOPE_MACRO", "COMPONENT_AT_AR_SUPP_02", "COMPONENT_ASSAULTSMG_VARMOD_LOWRIDER"};

//Rifles
const std::vector<std::string> CAPTIONS_ATTACH_ASSAULTRIFLE{"Extended Magazine", "Drum Magazine", "Flashlight", "Scope", "Suppressor", "Grip", "Yusuf Amir Luxury Finish"};
const std::vector<std::string> VALUES_ATTACH_ASSAULTRIFLE{"COMPONENT_ASSAULTRIFLE_CLIP_02", "COMPONENT_ASSAULTRIFLE_CLIP_03", "COMPONENT_AT_AR_FLSH", "COMPONENT_AT_SCOPE_MACRO", "COMPONENT_AT_AR_SUPP_02", "COMPONENT_AT_AR_AFGRIP", "COMPONENT_ASSAULTRIFLE_VARMOD_LUXE"};

const std::vector<std::string> CAPTIONS_ATTACH_CARBINERIFLE{"Extended Magazine", "Box Magazine", "Flashlight", "Scope", "Suppressor", "Grip", "Yusuf Amir Luxury Finish"};
const std::vector<std::string> VALUES_ATTACH_CARBINERIFLE{"COMPONENT_CARBINERIFLE_CLIP_02", "COMPONENT_CARBINERIFLE_CLIP_03", "COMPONENT_AT_AR_FLSH", "COMPONENT_AT_SCOPE_MEDIUM", "COMPONENT_AT_AR_SUPP", "COMPONENT_AT_AR_AFGRIP", "COMPONENT_CARBINERIFLE_VARMOD_LUXE"};

const std::vector<std::string> CAPTIONS_ATTACH_ADVANCEDRIFLE{"Extended Magazine", "Flashlight", "Scope", "Suppressor", "Gilded Gun Metal Finish"};
const std::vector<std::string> VALUES_ATTACH_ADVANCEDRIFLE{"COMPONENT_ADVANCEDRIFLE_CLIP_02", "COMPONENT_AT_AR_FLSH", "COMPONENT_AT_SCOPE_SMALL", "COMPONENT_AT_AR_SUPP", "COMPONENT_ADVANCEDRIFLE_VARMOD_LUXE"};

//Machine Guns
const std::vector<std::string> CAPTIONS_ATTACH_MG{"Extended Magazine", "Scope", "Yusuf Amir Luxury Finish"};
const std::vector<std::string> VALUES_ATTACH_MG{"COMPONENT_MG_CLIP_02", "COMPONENT_AT_SCOPE_SMALL_02", "COMPONENT_MG_VARMOD_LOWRIDER"};

const std::vector<std::string> CAPTIONS_ATTACH_COMBATMG{"Extended Magazine", "Scope", "Grip", "Etched Gun Metal Finish"};
const std::vector<std::string> VALUES_ATTACH_COMBATMG{"COMPONENT_COMBATMG_CLIP_02", "COMPONENT_AT_SCOPE_MEDIUM", "COMPONENT_AT_AR_AFGRIP", "COMPONENT_COMBATMG_VARMOD_LOWRIDER"};

//Shotguns
const std::vector<std::string> CAPTIONS_ATTACH_PUMPSHOTGUN{"Flashlight", "Suppressor", "Yusuf Amir Luxury Finish"};
const std::vector<std::string> VALUES_ATTACH_PUMPSHOTGUN{"COMPONENT_AT_AR_FLSH", "COMPONENT_AT_SR_SUPP", "COMPONENT_PUMPSHOTGUN_VARMOD_LOWRIDER"};

const std::vector<std::string> CAPTIONS_ATTACH_SAWNOFF{"Gilded Gun Metal Finish"};
const std::vector<std::string> VALUES_ATTACH_SAWNOFF{"COMPONENT_SAWNOFFSHOTGUN_VARMOD_LUXE"};

const std::vector<std::string> CAPTIONS_ATTACH_ASSAULTSHOTGUN{"Extended Magazine", "Flashlight", "Suppressor", "Grip"};
const std::vector<std::string> VALUES_ATTACH_ASSAULTSHOTGUN{"COMPONENT_ASSAULTSHOTGUN_CLIP_02", "COMPONENT_AT_AR_FLSH", "COMPONENT_AT_AR_SUPP", "COMPONENT_AT_AR_AFGRIP"};

const std::vector<std::string> CAPTIONS_ATTACH_BULLPUPSHOTGUN{"Flashlight", "Suppressor", "Grip"};
const std::vector<std::string> VALUES_ATTACH_BULLPUPSHOTGUN{"COMPONENT_AT_AR_FLSH", "COMPONENT_AT_AR_SUPP_02", "COMPONENT_AT_AR_AFGRIP"};

//Sniper Rifles
const std::vector<std::string> CAPTIONS_ATTACH_SNIPERRIFLE{"Suppressor", "Advanced Scope", "Etched Wood Grip Finish"};
const std::vector<std::string> VALUES_ATTACH_SNIPERRIFLE{"COMPONENT_AT_AR_SUPP_02", "COMPONENT_AT_SCOPE_MAX", "COMPONENT_SNIPERRIFLE_VARMOD_LUXE"};

const std::vector<std::string> CAPTIONS_ATTACH_HEAVYSNIPER{"Normal Scope"};
const std::vector<std::string> VALUES_ATTACH_HEAVYSNIPER{"COMPONENT_AT_SCOPE_LARGE"};

//Heavy Weapons
const std::vector<std::string> CAPTIONS_ATTACH_GRENADELAUNCHER{"Flashlight", "Grip", "Scope"};
const std::vector<std::string> VALUES_ATTACH_GRENADELAUNCHER{"COMPONENT_AT_AR_FLSH", "COMPONENT_AT_AR_AFGRIP", "COMPONENT_AT_SCOPE_SMALL"};

//DLC Weapons
const std::vector<std::string> CAPTIONS_ATTACH_BULLPUPRIFLE{"Extended Magazine", "Flashlight", "Scope", "Suppressor", "Grip", "Gilded Gun Metal Finish"};
const std::vector<std::string> VALUES_ATTACH_BULLPUPRIFLE{"COMPONENT_BULLPUPRIFLE_CLIP_02", "COMPONENT_AT_AR_FLSH", "COMPONENT_AT_SCOPE_SMALL", "COMPONENT_AT_AR_SUPP", "COMPONENT_AT_AR_AFGRIP", "COMPONENT_BULLPUPRIFLE_VARMOD_LOW"};

const std::vector<std::string> CAPTIONS_ATTACH_COMBATPDW{"Extended Magazine", "Drum Magazine", "Flashlight", "Grip", "Scope"};
const std::vector<std::string> VALUES_ATTACH_COMBATPDW{"COMPONENT_COMBATPDW_CLIP_02", "COMPONENT_COMBATPDW_CLIP_03", "COMPONENT_AT_AR_FLSH", "COMPONENT_AT_AR_AFGRIP", "COMPONENT_AT_SCOPE_SMALL"};

const std::vector<std::string> CAPTIONS_ATTACH_COMPACTRIFLE{"Extended Magazine", "Drum Magazine"};
const std::vector<std::string> VALUES_ATTACH_COMPACTRIFLE{"COMPONENT_COMPACTRIFLE_CLIP_02", "COMPONENT_COMPACTRIFLE_CLIP_03"};

const std::vector<std::string> CAPTIONS_ATTACH_GUSENBERG{"Extended Magazine"};
const std::vector<std::string> VALUES_ATTACH_GUSENBERG{"COMPONENT_GUSENBERG_CLIP_02"};

const std::vector<std::string> CAPTIONS_ATTACH_HEAVYPISTOL{"Extended Magazine", "Flashlight", "Suppressor", "Etched Wood Grip Finish"};
const std::vector<std::string> VALUES_ATTACH_HEAVYPISTOL{"COMPONENT_HEAVYPISTOL_CLIP_02", "COMPONENT_AT_PI_FLSH", "COMPONENT_AT_PI_SUPP", "COMPONENT_HEAVYPISTOL_VARMOD_LUXE"};

const std::vector<std::string> CAPTIONS_ATTACH_HEAVYSHOTGUN{"Extended Magazine", "Drum Magazine", "Flashlight", "Suppressor", "Grip"};
const std::vector<std::string> VALUES_ATTACH_HEAVYSHOTGUN{"COMPONENT_HEAVYSHOTGUN_CLIP_02", "COMPONENT_HEAVYSHOTGUN_CLIP_03", "COMPONENT_AT_AR_FLSH", "COMPONENT_AT_AR_SUPP_02", "COMPONENT_AT_AR_AFGRIP"};

const std::vector<std::string> CAPTIONS_ATTACH_KNUCKLES{"Default", "Pimp", "Ballas", "Dollars", "Diamond", "Hate", "Love", "Player", "King", "Vagos"};
const std::vector<std::string> VALUES_ATTACH_KNUCKLES{"COMPONENT_KNUCKLE_VARMOD_BASE", "COMPONENT_KNUCKLE_VARMOD_PIMP", "COMPONENT_KNUCKLE_VARMOD_BALLAS", "COMPONENT_KNUCKLE_VARMOD_DOLLAR", "COMPONENT_KNUCKLE_VARMOD_DIAMOND", "COMPONENT_KNUCKLE_VARMOD_HATE", "COMPONENT_KNUCKLE_VARMOD_LOVE", "COMPONENT_KNUCKLE_VARMOD_PLAYER", "COMPONENT_KNUCKLE_VARMOD_KING", "COMPONENT_KNUCKLE_VARMOD_VAGOS"};

const std::vector<std::string> CAPTIONS_ATTACH_MACHINEPISTOL{"Extended Magazine", "Drum Magazine", "Suppressor"};
const std::vector<std::string> VALUES_ATTACH_MACHINEPISTOL{"COMPONENT_MACHINEPISTOL_CLIP_02", "COMPONENT_MACHINEPISTOL_CLIP_03", "COMPONENT_AT_PI_SUPP"};

const std::vector<std::string> CAPTIONS_ATTACH_MARKSMANRIFLE{"Extended Magazine", "Flashlight", "Suppressor", "Grip", "Yusuf Amir Luxury Finish"};
const std::vector<std::string> VALUES_ATTACH_MARKSMANRIFLE{"COMPONENT_MARKSMANRIFLE_CLIP_02", "COMPONENT_AT_AR_FLSH", "COMPONENT_AT_AR_SUPP", "COMPONENT_AT_AR_AFGRIP", "COMPONENT_MARKSMANRIFLE_VARMOD_LUXE"};

const std::vector<std::string> CAPTIONS_ATTACH_MINISMG{"Extended Magazine"};
const std::vector<std::string> VALUES_ATTACH_MINISMG{"COMPONENT_MINISMG_CLIP_02"};

const std::vector<std::string> CAPTIONS_ATTACH_REVOLVER{"VIP Finish", "Bodyguard Finish"};
const std::vector<std::string> VALUES_ATTACH_REVOLVER{"COMPONENT_REVOLVER_VARMOD_BOSS", "COMPONENT_REVOLVER_VARMOD_GOON"};

const std::vector<std::string> CAPTIONS_ATTACH_SNSPISTOL{"Extended Magazine", "Etched Wood Grip Finish"};
const std::vector<std::string> VALUES_ATTACH_SNSPISTOL{"COMPONENT_SNSPISTOL_CLIP_02", "COMPONENT_SNSPISTOL_VARMOD_LOWRIDER"};

const std::vector<std::string> CAPTIONS_ATTACH_SPECIALCARBINE{"Extended Magazine", "Drum Magazine", "Flashlight", "Scope", "Suppressor", "Grip", "Etched Gun Metal Finish"};
const std::vector<std::string> VALUES_ATTACH_SPECIALCARBINE{"COMPONENT_SPECIALCARBINE_CLIP_02", "COMPONENT_SPECIALCARBINE_CLIP_03", "COMPONENT_AT_AR_FLSH", "COMPONENT_AT_SCOPE_MEDIUM", "COMPONENT_AT_AR_SUPP_02", "COMPONENT_AT_AR_AFGRIP", "COMPONENT_SPECIALCARBINE_VARMOD_LOWRIDER"};

const std::vector<std::string> CAPTIONS_ATTACH_SWITCHBLADE{"Default", "VIP Finish", "Bodyguard Finish"};
const std::vector<std::string> VALUES_ATTACH_SWITCHBLADE{"COMPONENT_SWITCHBLADE_VARMOD_BASE", "COMPONENT_SWITCHBLADE_VARMOD_VAR1", "COMPONENT_SWITCHBLADE_VARMOD_VAR2"};

const std::vector<std::string> CAPTIONS_ATTACH_VINTAGEPISTOL{"Extended Magazine", "Suppressor"};
const std::vector<std::string> VALUES_ATTACH_VINTAGEPISTOL{"COMPONENT_VINTAGEPISTOL_CLIP_02", "COMPONENT_AT_PI_SUPP"};

/*Gun Running DLC*/
const std::vector<std::string> CAPTIONS_ATTACH_PISTOLMK2{ "Default Clip", "Extended Clip", "Tracer Rounds", "Incendiary Rounds", "Hollow Point Rounds", "Full-Metal Jacket Rounds", "Component Rail", "Flashlight", "Suppressor", "Extended Muzzle", "Digital Camo", "Zebra Camo", "Green Camo", "Skull Camo", "Diamond Camo", "Designer Camo", "Zebra Camo 2", "White Tiger Camo", "Urban Camo", "Boom! Camo", "Independance Day Camo" };
const std::vector<std::string> VALUES_ATTACH_PISTOLMK2{ "COMPONENT_PISTOL_MK2_CLIP_01", "COMPONENT_PISTOL_MK2_CLIP_02", "COMPONENT_PISTOL_MK2_CLIP_TRACER", "COMPONENT_PISTOL_MK2_CLIP_INCENDIARY", "COMPONENT_PISTOL_MK2_CLIP_HOLLOWPOINT", "COMPONENT_PISTOL_MK2_CLIP_FMJ", "COMPONENT_AT_PI_RAIL", "COMPONENT_AT_PI_FLSH_02", "COMPONENT_AT_PI_SUPP_02", "COMPONENT_AT_PI_COMP", "COMPONENT_PISTOL_MK2_CAMO", "COMPONENT_PISTOL_MK2_CAMO_02", "COMPONENT_PISTOL_MK2_CAMO_03", "COMPONENT_PISTOL_MK2_CAMO_04", "COMPONENT_PISTOL_MK2_CAMO_05", "COMPONENT_PISTOL_MK2_CAMO_06", "COMPONENT_PISTOL_MK2_CAMO_07", "COMPONENT_PISTOL_MK2_CAMO_08", "COMPONENT_PISTOL_MK2_CAMO_09", "COMPONENT_PISTOL_MK2_CAMO_10", "COMPONENT_PISTOL_MK2_CAMO_IND_01" };

const std::vector<std::string> CAPTIONS_ATTACH_SMGMK2{ "Default Clip", "Extended Clip", "Tracer Rounds", "Incendiary Rounds", "Hollow Point Rounds", "Full-Metal Jacket Rounds", "Flashlight", "Improved Sights", "Macro Scope", " Small Scope", "Suppressor", "Muzzle 1", "Muzzle 2", "Muzzle 3", "Muzzle 4", "Muzzle 5", "Muzzle 6", "Muzzle 7", "SB Barrel 1", "SB Barrel 2", "Digital Camo", "Zebra Camo", "Green Camo", "Skull Camo", "Diamond Camo", "Designer Camo", "Zebra Camo 2", "White Tiger Camo", "Urban Camo", "Boom! Camo", "Independance Day Camo", };
const std::vector<std::string> VALUES_ATTACH_SMGMK2{ "COMPONENT_SMG_MK2_CLIP_01", "COMPONENT_SMG_MK2_CLIP_02", "COMPONENT_SMG_MK2_CLIP_TRACER", "COMPONENT_SMG_MK2_CLIP_INCENDIARY", "COMPONENT_SMG_MK2_CLIP_HOLLOWPOINT", "COMPONENT_SMG_MK2_CLIP_FMJ", "COMPONENT_AT_AR_FLSH", "COMPONENT_AT_SIGHTS_SMG", "COMPONENT_AT_SCOPE_MACRO_02_SMG_MK2", "COMPONENT_AT_SCOPE_SMALL_SMG_MK2", "COMPONENT_AT_PI_SUPP", "COMPONENT_AT_MUZZLE_01", "COMPONENT_AT_MUZZLE_02", "COMPONENT_AT_MUZZLE_03", "COMPONENT_AT_MUZZLE_04", "COMPONENT_AT_MUZZLE_05", "COMPONENT_AT_MUZZLE_06", "COMPONENT_AT_MUZZLE_07", "COMPONENT_AT_SB_BARREL_01", "COMPONENT_AT_SB_BARREL_02", "COMPONENT_SMG_MK2_CAMO", "COMPONENT_SMG_MK2_CAMO_02", "COMPONENT_SMG_MK2_CAMO_03", "COMPONENT_SMG_MK2_CAMO_04", "COMPONENT_SMG_MK2_CAMO_05", "COMPONENT_SMG_MK2_CAMO_06", "COMPONENT_SMG_MK2_CAMO_07", "COMPONENT_SMG_MK2_CAMO_08", "COMPONENT_SMG_MK2_CAMO_09", "COMPONENT_SMG_MK2_CAMO_10", "COMPONENT_SMG_MK2_CAMO_IND_01", };

const std::vector<std::string> CAPTIONS_ATTACH_ASSAULTRIFLEMK2{ "Default Clip", "Extended Clip", "Tracer Rounds", "Incendiary Rounds", "Armour Piercing Rounds", "Full-Metal Jacket Rounds", "AF Grip", "Flashlight", "Improved Sights", "Macro Scope", "Medium Scope", "Suppressor 2", "Muzzle 1", "Muzzle 2", "Muzzle 3", "Muzzle 4", "Muzzle 5", "Muzzle 6", "Muzzle 7", "Stock Barrel", "Improved Barrel", "Digital Camo", "Zebra Camo", "Green Camo", "Skull Camo", "Diamond Camo", "Designer Camo", "Zebra Camo 2", "White Tiger Camo", "Urban Camo", "Boom! Camo", "Independance Day Camo" };
const std::vector<std::string> VALUES_ATTACH_ASSAULTRIFLEMK2{ "COMPONENT_ASSAULTRIFLE_MK2_CLIP_01", "COMPONENT_ASSAULTRIFLE_MK2_CLIP_02", "COMPONENT_ASSAULTRIFLE_MK2_CLIP_TRACER", "COMPONENT_ASSAULTRIFLE_MK2_CLIP_INCENDIARY", "COMPONENT_ASSAULTRIFLE_MK2_CLIP_ARMORPIERCING", "COMPONENT_ASSAULTRIFLE_MK2_CLIP_FMJ", "COMPONENT_AT_AR_AFGRIP_02", "COMPONENT_AT_AR_FLSH", "COMPONENT_AT_SIGHTS", "COMPONENT_AT_SCOPE_MACRO_MK2", "COMPONENT_AT_SCOPE_MEDIUM_MK2", "COMPONENT_AT_AR_SUPP_02", "COMPONENT_AT_MUZZLE_01", "COMPONENT_AT_MUZZLE_02", "COMPONENT_AT_MUZZLE_03", "COMPONENT_AT_MUZZLE_04", "COMPONENT_AT_MUZZLE_05", "COMPONENT_AT_MUZZLE_06", "COMPONENT_AT_MUZZLE_07", "COMPONENT_AT_AR_BARREL_01", "COMPONENT_AT_AR_BARREL_02", "COMPONENT_ASSAULTRIFLE_MK2_CAMO", "COMPONENT_ASSAULTRIFLE_MK2_CAMO_02", "COMPONENT_ASSAULTRIFLE_MK2_CAMO_03", "COMPONENT_ASSAULTRIFLE_MK2_CAMO_04", "COMPONENT_ASSAULTRIFLE_MK2_CAMO_05", "COMPONENT_ASSAULTRIFLE_MK2_CAMO_06", "COMPONENT_ASSAULTRIFLE_MK2_CAMO_07", "COMPONENT_ASSAULTRIFLE_MK2_CAMO_08", "COMPONENT_ASSAULTRIFLE_MK2_CAMO_09", "COMPONENT_ASSAULTRIFLE_MK2_CAMO_10", "COMPONENT_ASSAULTRIFLE_MK2_CAMO_IND_01" };

const std::vector<std::string> CAPTIONS_ATTACH_CARBINERIFLEMK2{ "Default Clip", "Extended Clip", "Tracer Rounds", "Incendiary Rounds", "Armour Piercing Rounds", "Full-Metal Jacket Rounds", "AF Grip", "Flashlight", "Improved Sights", "Macro Scope", "Medium Scope", "Suppressor", "Muzzle 1", "Muzzle 2", "Muzzle 3", "Muzzle 4", "Muzzle 5", "Muzzle 6", "Muzzle 7", "CR Barrel 1", "CR Barrel 2", "Digital Camo", "Zebra Camo", "Green Camo", "Skull Camo", "Diamond Camo", "Designer Camo", "Zebra Camo 2", "White Tiger Camo", "Urban Camo", "Boom! Camo", "Independance Day Camo" };
const std::vector<std::string> VALUES_ATTACH_CARBINERIFLEMK2{ "COMPONENT_CARBINERIFLE_MK2_CLIP_01", "COMPONENT_CARBINERIFLE_MK2_CLIP_02", "COMPONENT_CARBINERIFLE_MK2_CLIP_TRACER", "COMPONENT_CARBINERIFLE_MK2_CLIP_INCENDIARY", "COMPONENT_CARBINERIFLE_MK2_CLIP_ARMORPIERCING", "COMPONENT_CARBINERIFLE_MK2_CLIP_FMJ", "COMPONENT_AT_AR_AFGRIP_02", "COMPONENT_AT_AR_FLSH", "COMPONENT_AT_SIGHTS", "COMPONENT_AT_SCOPE_MACRO_MK2", "COMPONENT_AT_SCOPE_MEDIUM_MK2", "COMPONENT_AT_AR_SUPP", "COMPONENT_AT_MUZZLE_01", "COMPONENT_AT_MUZZLE_02", "COMPONENT_AT_MUZZLE_03", "COMPONENT_AT_MUZZLE_04", "COMPONENT_AT_MUZZLE_05", "COMPONENT_AT_MUZZLE_06", "COMPONENT_AT_MUZZLE_07", "COMPONENT_AT_CR_BARREL_01", "COMPONENT_AT_CR_BARREL_02", "COMPONENT_CARBINERIFLE_MK2_CAMO", "COMPONENT_CARBINERIFLE_MK2_CAMO_02", "COMPONENT_CARBINERIFLE_MK2_CAMO_03", "OMPONENT_CARBINERIFLE_MK2_CAMO_04", "COMPONENT_CARBINERIFLE_MK2_CAMO_05", "COMPONENT_CARBINERIFLE_MK2_CAMO_06", "COMPONENT_CARBINERIFLE_MK2_CAMO_07", "COMPONENT_CARBINERIFLE_MK2_CAMO_08", "COMPONENT_CARBINERIFLE_MK2_CAMO_09", "COMPONENT_CARBINERIFLE_MK2_CAMO_10", "COMPONENT_CARBINERIFLE_MK2_CAMO_IND_01" };

const std::vector<std::string> CAPTIONS_ATTACH_COMBATMGMK2{ "Default Clip", "Extended Clip", "Tracer Rounds", "Incendiary Rounds", "Armour Piercing Rounds", "Full-Metal Jacket Rounds", "AF Grip", "Improved Sights", "Small Scope", "Medium Scope", "Muzzle 1", "Muzzle 2", "Muzzle 3", "Muzzle 4", "Muzzle 5", "Muzzle 6", "Muzzle 7", "Stock Barrel", "Improved Barrel", "Digital Camo", "Zebra Camo", "Green Camo", "Skull Camo", "Diamond Camo", "Designer Camo", "Zebra Camo 2", "White Tiger Camo", "Urban Camo", "Boom! Camo", "Independance Day Camo" };
const std::vector<std::string> VALUES_ATTACH_COMBATMGMK2{ "COMPONENT_COMBATMG_MK2_CLIP_01", "COMPONENT_COMBATMG_MK2_CLIP_02", "COMPONENT_COMBATMG_MK2_CLIP_TRACER", "COMPONENT_COMBATMG_MK2_CLIP_INCENDIARY", "COMPONENT_COMBATMG_MK2_CLIP_ARMORPIERCING", "COMPONENT_COMBATMG_MK2_CLIP_FMJ", "COMPONENT_AT_AR_AFGRIP_02", "COMPONENT_AT_SIGHTS", "COMPONENT_AT_SCOPE_SMALL_MK2", "COMPONENT_AT_SCOPE_MEDIUM_MK2", "COMPONENT_AT_MUZZLE_01", "COMPONENT_AT_MUZZLE_02", "COMPONENT_AT_MUZZLE_03", "COMPONENT_AT_MUZZLE_04", "COMPONENT_AT_MUZZLE_05", "COMPONENT_AT_MUZZLE_06", "COMPONENT_AT_MUZZLE_07", "COMPONENT_AT_MG_BARREL_01", "COMPONENT_AT_MG_BARREL_02", "COMPONENT_COMBATMG_MK2_CAMO", "COMPONENT_COMBATMG_MK2_CAMO_02", "COMPONENT_COMBATMG_MK2_CAMO_03", "COMPONENT_COMBATMG_MK2_CAMO_04", "COMPONENT_COMBATMG_MK2_CAMO_05", "COMPONENT_COMBATMG_MK2_CAMO_06", "COMPONENT_COMBATMG_MK2_CAMO_07", "COMPONENT_COMBATMG_MK2_CAMO_08", "COMPONENT_COMBATMG_MK2_CAMO_09", "COMPONENT_COMBATMG_MK2_CAMO_10", "COMPONENT_COMBATMG_MK2_CAMO_IND_01" };

const std::vector<std::string> CAPTIONS_ATTACH_HEAVYSNIPERMK2{ "Default Clip", "Extended Clip", "Incendiary Rounds", "Armour Piercing Rounds", "Full-Metal Jacket Rounds", "Explosive Rounds", "Large Scope", "Long Sight Scope", "Nightvision Scope", "Thermal Scope", "Suppressor", "Muzzle 1", "Muzzle 2", "SR Barrel 1", "SR Barrel 2", "Digital Camo", "Zebra Camo", "Green Camo", "Skull Camo", "Diamond Camo", "Designer Camo", "Zebra Camo 2", "White Tiger Camo", "Urban Camo", "Boom! Camo", "Independance Day Camo" };
const std::vector<std::string> VALUES_ATTACH_HEAVYSNIPERMK2{ "COMPONENT_HEAVYSNIPER_MK2_CLIP_01", "COMPONENT_HEAVYSNIPER_MK2_CLIP_02", "COMPONENT_HEAVYSNIPER_MK2_CLIP_INCENDIARY", "COMPONENT_HEAVYSNIPER_MK2_CLIP_ARMORPIERCING", "COMPONENT_HEAVYSNIPER_MK2_CLIP_FMJ", "COMPONENT_HEAVYSNIPER_MK2_CLIP_EXPLOSIVE", "COMPONENT_AT_SCOPE_LARGE_MK2", "COMPONENT_AT_SCOPE_MAX", "COMPONENT_AT_SCOPE_NV", "COMPONENT_AT_SCOPE_THERMAL", "COMPONENT_AT_SR_SUPP_03", "COMPONENT_AT_MUZZLE_08", "COMPONENT_AT_MUZZLE_09", "COMPONENT_AT_SR_BARREL_01", "COMPONENT_AT_SR_BARREL_02", "COMPONENT_HEAVYSNIPER_MK2_CAMO", "COMPONENT_HEAVYSNIPER_MK2_CAMO_02", "COMPONENT_HEAVYSNIPER_MK2_CAMO_03", "COMPONENT_HEAVYSNIPER_MK2_CAMO_04", "COMPONENT_HEAVYSNIPER_MK2_CAMO_05", "COMPONENT_HEAVYSNIPER_MK2_CAMO_06", "COMPONENT_HEAVYSNIPER_MK2_CAMO_07", "COMPONENT_HEAVYSNIPER_MK2_CAMO_08", "COMPONENT_HEAVYSNIPER_MK2_CAMO_09", "COMPONENT_HEAVYSNIPER_MK2_CAMO_10", "COMPONENT_HEAVYSNIPER_MK2_CAMO_IND_01" };


/*Doomsday Heist*/
const std::vector<std::string> CAPTIONS_ATTACH_SNSPISTOLMK2{ "Default Clip", "Extended Clip", "Tracer Rounds", "Incendiary Rounds", "Armour Piercing Rounds", "Full-Metal Jacket Rounds", "Flashlight", "Component Rail", "Suppressor", "Flash Hider", "Digital Camo", "Zebra Camo", "Green Camo", "Skull Camo", "Diamond Camo", "Designer Camo", "Zebra Camo 2", "White Tiger Camo", "Urban Camo", "Boom! Camo", "Independance Day Camo" };
const std::vector<std::string> VALUES_ATTACH_SNSPISTOLMK2{ "COMPONENT_SNSPISTOL_MK2_CLIP_01", "COMPONENT_SNSPISTOL_MK2_CLIP_02", "COMPONENT_SNSPISTOL_MK2_CLIP_TRACER", "COMPONENT_SNSPISTOL_MK2_CLIP_INCENDIARY", "COMPONENT_SNSPISTOL_MK2_CLIP_HOLLOWPOINT", "COMPONENT_SNSPISTOL_MK2_CLIP_FMJ", "COMPONENT_AT_PI_FLSH_03", "COMPONENT_AT_PI_RAIL_02", "COMPONENT_AT_PI_SUPP_02", "COMPONENT_AT_PI_COMP_02", "COMPONENT_SNSPISTOL_MK2_CAMO", "COMPONENT_SNSPISTOL_MK2_CAMO_02", "COMPONENT_SNSPISTOL_MK2_CAMO_03", "COMPONENT_SNSPISTOL_MK2_CAMO_04", "COMPONENT_SNSPISTOL_MK2_CAMO_05", "COMPONENT_SNSPISTOL_MK2_CAMO_06", "COMPONENT_SNSPISTOL_MK2_CAMO_07", "COMPONENT_SNSPISTOL_MK2_CAMO_08", "COMPONENT_SNSPISTOL_MK2_CAMO_09", "COMPONENT_SNSPISTOL_MK2_CAMO_10", "COMPONENT_SNSPISTOL_MK2_CAMO_IND_01"};

const std::vector<std::string> CAPTIONS_ATTACH_REVOLVERMK2{ "Default Clip", "Tracer Rounds", "Incendiary Rounds", "Armour Piercing Rounds", "Full-Metal Jacket Rounds", "Improved Sights", "Macro Scope", "Flashlight", "Barrel Extension", "Digital Camo", "Zebra Camo", "Green Camo", "Skull Camo", "Diamond Camo", "Designer Camo", "Zebra Camo 2", "White Tiger Camo", "Urban Camo", "Boom! Camo", "Independance Day Camo" };
const std::vector<std::string> VALUES_ATTACH_REVOLVERMK2{ "COMPONENT_REVOLVER_MK2_CLIP_01", "COMPONENT_REVOLVER_MK2_CLIP_TRACER", "COMPONENT_REVOLVER_MK2_CLIP_INCENDIARY", "COMPONENT_REVOLVER_MK2_CLIP_HOLLOWPOINT", "COMPONENT_REVOLVER_MK2_CLIP_FMJ", "COMPONENT_AT_SIGHTS", "COMPONENT_AT_SCOPE_MACRO_MK2", "COMPONENT_AT_PI_FLSH", "COMPONENT_AT_PI_COMP_03", "COMPONENT_REVOLVER_MK2_CAMO", "COMPONENT_REVOLVER_MK2_CAMO_02", "COMPONENT_REVOLVER_MK2_CAMO_03", "COMPONENT_REVOLVER_MK2_CAMO_04", "COMPONENT_REVOLVER_MK2_CAMO_05", "COMPONENT_REVOLVER_MK2_CAMO_06", "COMPONENT_REVOLVER_MK2_CAMO_07", "COMPONENT_REVOLVER_MK2_CAMO_08", "COMPONENT_REVOLVER_MK2_CAMO_09", "COMPONENT_REVOLVER_MK2_CAMO_10", "COMPONENT_REVOLVER_MK2_CAMO_IND_01" };

const std::vector<std::string> CAPTIONS_ATTACH_SPECIALCARBINEMK2{ "Default Clip", "Extended Clip", "Tracer Rounds", "Incendiary Rounds", "Armour Piercing Rounds", "Full-Metal Jacket Rounds", "Flashlight", "Improved Sights", "Macro Scope", "Medium Scope", "Suppressor", "Muzzle 1", "Muzzle 2", "Muzzle 3", "Muzzle 4", "Muzzle 5", "Muzzle 6", "Muzzle 7", "Improved Grip", "Barrel 1", "Barrel 2", "Digital Camo", "Zebra Camo", "Green Camo", "Skull Camo", "Diamond Camo", "Designer Camo", "Zebra Camo 2", "White Tiger Camo", "Urban Camo", "Boom! Camo", "Independance Day Camo" };
const std::vector<std::string> VALUES_ATTACH_SPECIALCARBINEMK2{ "COMPONENT_SPECIALCARBINE_MK2_CLIP_01", "COMPONENT_SPECIALCARBINE_MK2_CLIP_02", "COMPONENT_SPECIALCARBINE_MK2_CLIP_TRACER", "COMPONENT_SPECIALCARBINE_MK2_CLIP_INCENDIARY", "COMPONENT_SPECIALCARBINE_MK2_CLIP_ARMORPIERCING", "COMPONENT_SPECIALCARBINE_MK2_CLIP_FMJ", "COMPONENT_AT_AR_FLSH", "COMPONENT_AT_SIGHTS", "COMPONENT_AT_SCOPE_MACRO_MK2", "COMPONENT_AT_SCOPE_MEDIUM_MK2", "COMPONENT_AT_AR_SUPP_02", "COMPONENT_AT_MUZZLE_01", "COMPONENT_AT_MUZZLE_02", "COMPONENT_AT_MUZZLE_03", "COMPONENT_AT_MUZZLE_04", "COMPONENT_AT_MUZZLE_05", "COMPONENT_AT_MUZZLE_06", "COMPONENT_AT_MUZZLE_07", "COMPONENT_AT_AR_AFGRIP_02", "COMPONENT_AT_SC_BARREL_01", "COMPONENT_AT_SC_BARREL_02", "COMPONENT_SPECIALCARBINE_MK2_CAMO", "COMPONENT_SPECIALCARBINE_MK2_CAMO_02", "COMPONENT_SPECIALCARBINE_MK2_CAMO_03", "COMPONENT_SPECIALCARBINE_MK2_CAMO_04", "COMPONENT_SPECIALCARBINE_MK2_CAMO_05", "COMPONENT_SPECIALCARBINE_MK2_CAMO_06", "COMPONENT_SPECIALCARBINE_MK2_CAMO_07", "COMPONENT_SPECIALCARBINE_MK2_CAMO_08", "COMPONENT_SPECIALCARBINE_MK2_CAMO_09", "COMPONENT_SPECIALCARBINE_MK2_CAMO_10", "COMPONENT_SPECIALCARBINE_MK2_CAMO_IND_01" };

const std::vector<std::string> CAPTIONS_ATTACH_BULLPUPMK2{ "Default Clip", "Extended Clip", "Tracer Rounds", "Incendiary Rounds", "Armour Piercing Rounds", "Full-Metal Jacket Rounds", "Flashlight", "Improved Sights", "Macro Scope", "Small Scope", "Barrel 1", "Barrel 2", "Suppressor", "Muzzle 1", "Muzzle 2", "Muzzle 3", "Muzzle 4", "Muzzle 5", "Muzzle 6", "Muzzle 7", "Improved Grip", "Digital Camo", "Zebra Camo", "Green Camo", "Skull Camo", "Diamond Camo", "Designer Camo", "Zebra Camo 2", "White Tiger Camo", "Urban Camo", "Boom! Camo", "Independance Day Camo" };
const std::vector<std::string> VALUES_ATTACH_BULLPUPMK2{ "COMPONENT_BULLPUPRIFLE_MK2_CLIP_01", "COMPONENT_BULLPUPRIFLE_MK2_CLIP_02", "COMPONENT_BULLPUPRIFLE_MK2_CLIP_TRACER", "COMPONENT_BULLPUPRIFLE_MK2_CLIP_INCENDIARY", "COMPONENT_BULLPUPRIFLE_MK2_CLIP_ARMORPIERCING", "COMPONENT_BULLPUPRIFLE_MK2_CLIP_FMJ", "COMPONENT_AT_AR_FLSH", "COMPONENT_AT_SIGHTS", "COMPONENT_AT_SCOPE_MACRO_02_MK2", "COMPONENT_AT_SCOPE_SMALL_MK2", "COMPONENT_AT_BP_BARREL_01", "COMPONENT_AT_BP_BARREL_02", "COMPONENT_AT_AR_SUPP", "COMPONENT_AT_MUZZLE_01", "COMPONENT_AT_MUZZLE_02", "COMPONENT_AT_MUZZLE_03", "COMPONENT_AT_MUZZLE_04","COMPONENT_AT_MUZZLE_05","COMPONENT_AT_MUZZLE_06","COMPONENT_AT_MUZZLE_07","COMPONENT_AT_AR_AFGRIP_02","COMPONENT_BULLPUPRIFLE_MK2_CAMO","COMPONENT_BULLPUPRIFLE_MK2_CAMO_02","COMPONENT_BULLPUPRIFLE_MK2_CAMO_03","COMPONENT_BULLPUPRIFLE_MK2_CAMO_04","COMPONENT_BULLPUPRIFLE_MK2_CAMO_05", "COMPONENT_BULLPUPRIFLE_MK2_CAMO_06", "COMPONENT_BULLPUPRIFLE_MK2_CAMO_07", "COMPONENT_BULLPUPRIFLE_MK2_CAMO_08", "COMPONENT_BULLPUPRIFLE_MK2_CAMO_09", "COMPONENT_BULLPUPRIFLE_MK2_CAMO_10", "COMPONENT_BULLPUPRIFLE_MK2_CAMO_IND_01" };

const std::vector<std::string> CAPTIONS_ATTACH_PUMPSHOTGUNMK2{ "Default Clip", "Dragonbreath Rounds", "Armour Piercing Rounds", "Hollowpoint Rounds", "Explosive Rounds", "Improved Sights", "Macro Scope", "Small Scope", "Flashlight", "Suppressor", "Flash Hider", "Digital Camo", "Zebra Camo", "Green Camo", "Skull Camo", "Diamond Camo", "Designer Camo", "Zebra Camo 2", "White Tiger Camo", "Urban Camo", "Boom! Camo", "Independance Day Camo" };
const std::vector<std::string> VALUES_ATTACH_PUMPSHOTGUNMK2{ "COMPONENT_PUMPSHOTGUN_MK2_CLIP_01", "COMPONENT_PUMPSHOTGUN_MK2_CLIP_INCENDIARY", "COMPONENT_PUMPSHOTGUN_MK2_CLIP_ARMORPIERCING", "COMPONENT_PUMPSHOTGUN_MK2_CLIP_HOLLOWPOINT", "COMPONENT_PUMPSHOTGUN_MK2_CLIP_EXPLOSIVE", "COMPONENT_AT_SIGHTS", "COMPONENT_AT_SCOPE_MACRO_MK2", "COMPONENT_AT_SCOPE_SMALL_MK2", "COMPONENT_AT_AR_FLSH", "COMPONENT_AT_SR_SUPP_03", "COMPONENT_AT_MUZZLE_08", "COMPONENT_PUMPSHOTGUN_MK2_CAMO", "COMPONENT_PUMPSHOTGUN_MK2_CAMO_02", "COMPONENT_PUMPSHOTGUN_MK2_CAMO_03", "COMPONENT_PUMPSHOTGUN_MK2_CAMO_04", "COMPONENT_PUMPSHOTGUN_MK2_CAMO_05", "COMPONENT_PUMPSHOTGUN_MK2_CAMO_06", "COMPONENT_PUMPSHOTGUN_MK2_CAMO_07", "COMPONENT_PUMPSHOTGUN_MK2_CAMO_08", "COMPONENT_PUMPSHOTGUN_MK2_CAMO_09", "COMPONENT_PUMPSHOTGUN_MK2_CAMO_10", "COMPONENT_PUMPSHOTGUN_MK2_CAMO_IND_01" };

const std::vector<std::string> CAPTIONS_ATTACH_MARKSMANRIFLEMK2{ "Default Clip", "Extended Clip", "Tracer Rounds", "Incendiary Rounds", "Armour Piercing Rounds", "Full-Metal Jacket Rounds", "Improved Sights", "Medium Scope", "Long Range Scope", "Flashlight", "Suppressor", "Muzzle 1", "Muzzle 2", "Muzzle 3", "Muzzle 4", "Muzzle 5", "Muzzle 6", "Muzzle 7", "Barrel 1", "Barrel 2", "Improved Grip", "Digital Camo", "Zebra Camo", "Green Camo", "Skull Camo", "Diamond Camo", "Designer Camo", "Zebra Camo 2", "White Tiger Camo", "Urban Camo", "Boom! Camo", "Independance Day Camo" };
const std::vector<std::string> VALUES_ATTACH_MARKSMANRIFLEMK2{ "COMPONENT_MARKSMANRIFLE_MK2_CLIP_01", "COMPONENT_MARKSMANRIFLE_MK2_CLIP_02", "COMPONENT_MARKSMANRIFLE_MK2_CLIP_TRACER", "COMPONENT_MARKSMANRIFLE_MK2_CLIP_INCENDIARY", "COMPONENT_MARKSMANRIFLE_MK2_CLIP_ARMORPIERCING", "COMPONENT_MARKSMANRIFLE_MK2_CLIP_FMJ", "COMPONENT_AT_SIGHTS", "COMPONENT_AT_SCOPE_MEDIUM_MK2", "COMPONENT_AT_SCOPE_LARGE_FIXED_ZOOM_MK2", "COMPONENT_AT_AR_FLSH", "COMPONENT_AT_AR_SUPP", "COMPONENT_AT_MUZZLE_01", "COMPONENT_AT_MUZZLE_02", "COMPONENT_AT_MUZZLE_03", "COMPONENT_AT_MUZZLE_04", "COMPONENT_AT_MUZZLE_05", "COMPONENT_AT_MUZZLE_06", "COMPONENT_AT_MUZZLE_07", "COMPONENT_AT_MRFL_BARREL_01", "COMPONENT_AT_MRFL_BARREL_02", "COMPONENT_AT_AR_AFGRIP_02", "COMPONENT_MARKSMANRIFLE_MK2_CAMO", "COMPONENT_MARKSMANRIFLE_MK2_CAMO_02", "COMPONENT_MARKSMANRIFLE_MK2_CAMO_03", "COMPONENT_MARKSMANRIFLE_MK2_CAMO_04", "COMPONENT_MARKSMANRIFLE_MK2_CAMO_05", "COMPONENT_MARKSMANRIFLE_MK2_CAMO_06", "COMPONENT_MARKSMANRIFLE_MK2_CAMO_07", "COMPONENT_MARKSMANRIFLE_MK2_CAMO_08", "COMPONENT_MARKSMANRIFLE_MK2_CAMO_09", "COMPONENT_MARKSMANRIFLE_MK2_CAMO_10", "COMPONENT_MARKSMANRIFLE_MK2_CAMO_IND_01" };


//Tintable weapons list
const std::vector<std::string> WEAPONTYPES_TINT{ "WEAPON_PISTOL", "WEAPON_COMBATPISTOL", "WEAPON_APPISTOL", "WEAPON_PISTOL50", "WEAPON_SNSPISTOL", "WEAPON_HEAVYPISTOL", "WEAPON_VINTAGEPISTOL", "WEAPON_STUNGUN", "WEAPON_FLAREGUN", "WEAPON_MARKSMANPISTOL", "WEAPON_MICROSMG", "WEAPON_SMG", "WEAPON_ASSAULTSMG", "WEAPON_MG", "WEAPON_COMBATMG", "WEAPON_GUSENBERG", "WEAPON_ASSAULTRIFLE", "WEAPON_CARBINERIFLE", "WEAPON_ADVANCEDRIFLE", "WEAPON_SPECIALCARBINE", "WEAPON_BULLPUPRIFLE", "WEAPON_PUMPSHOTGUN", "WEAPON_SAWNOFFSHOTGUN", "WEAPON_BULLPUPSHOTGUN", "WEAPON_ASSAULTSHOTGUN", "WEAPON_MUSKET", "WEAPON_HEAVYSHOTGUN", "WEAPON_SNIPERRIFLE", "WEAPON_HEAVYSNIPER", "WEAPON_MARKSMANRIFLE", "WEAPON_GRENADELAUNCHER", "WEAPON_RPG", "WEAPON_MINIGUN", "WEAPON_FIREWORK", "WEAPON_RAILGUN", "WEAPON_HOMINGLAUNCHER", "WEAPON_COMBATPDW", "WEAPON_MACHINEPISTOL", "WEAPON_DBSHOTGUN", "WEAPON_COMPACTRIFLE", "WEAPON_AUTOSHOTGUN", "WEAPON_COMPACTLAUNCHER", "WEAPON_MINISMG", "WEAPON_PISTOL_MK2", "WEAPON_SMG_MK2", "WEAPON_ASSAULTRIFLE_MK2", "WEAPON_CARBINERIFLE_MK2", "WEAPON_COMBATMG_MK2", "WEAPON_HEAVYSNIPER_MK2", /*"WEAPON_SNSPISTOL_MK2", "WEAPON_REVOLVER_MK2", "WEAPON_SPECIALCARBINE_MK2", "WEAPON_BULLPUPRIFLE_MK2", "WEAPON_PUMPSHOTGUN_MK2", "WEAPON_MARKSMANRIFLE_MK2", WEAPON_DOUBLEACTION*/ };

//moddable weapons list
const std::vector<std::string> WEAPONTYPES_MOD{ "WEAPON_PISTOL", "WEAPON_HEAVYPISTOL", "WEAPON_COMBATPISTOL", "WEAPON_APPISTOL", "WEAPON_PISTOL50", "WEAPON_MICROSMG", "WEAPON_SMG", "WEAPON_ASSAULTSMG", "WEAPON_ASSAULTRIFLE", "WEAPON_CARBINERIFLE", "WEAPON_ADVANCEDRIFLE", "WEAPON_MG", "WEAPON_COMBATMG", "WEAPON_SAWNOFFSHOTGUN", "WEAPON_PUMPSHOTGUN", "WEAPON_ASSAULTSHOTGUN", "WEAPON_BULLPUPSHOTGUN", "WEAPON_SNIPERRIFLE", "WEAPON_HEAVYSNIPER", "WEAPON_GRENADELAUNCHER", "WEAPON_BULLPUPRIFLE", "WEAPON_GUSENBERG", "WEAPON_HEAVYSHOTGUN", "WEAPON_MARKSMANRIFLE", "WEAPON_SNSPISTOL", "WEAPON_SPECIALCARBINE", "WEAPON_VINTAGEPISTOL", "WEAPON_COMBATPDW", "WEAPON_MACHINEPISTOL", "WEAPON_SWITCHBLADE", "WEAPON_REVOLVER", "WEAPON_COMPACTRIFLE", "WEAPON_MINISMG", "WEAPON_PISTOL_MK2", "WEAPON_SMG_MK2", "WEAPON_ASSAULTRIFLE_MK2", "WEAPON_CARBINERIFLE_MK2", "WEAPON_COMBATMG_MK2", "WEAPON_HEAVYSNIPER_MK2", "WEAPON_SNSPISTOL_MK2", "WEAPON_REVOLVER_MK2", "WEAPON_SPECIALCARBINE_MK2", "WEAPON_BULLPUPRIFLE_MK2", "WEAPON_PUMPSHOTGUN_MK2" };

const std::vector<std::string> VOV_WEAPONMOD_CAPTIONS[] = { CAPTIONS_ATTACH_PISTOL, CAPTIONS_ATTACH_HEAVYPISTOL, CAPTIONS_ATTACH_COMBATPISTOL, CAPTIONS_ATTACH_APPISTOL, CAPTIONS_ATTACH_PISTOL50, CAPTIONS_ATTACH_MICROSMG, CAPTIONS_ATTACH_SMG, CAPTIONS_ATTACH_ASSAULTSMG, CAPTIONS_ATTACH_ASSAULTRIFLE, CAPTIONS_ATTACH_CARBINERIFLE, CAPTIONS_ATTACH_ADVANCEDRIFLE, CAPTIONS_ATTACH_MG, CAPTIONS_ATTACH_COMBATMG, CAPTIONS_ATTACH_SAWNOFF, CAPTIONS_ATTACH_PUMPSHOTGUN, CAPTIONS_ATTACH_ASSAULTSHOTGUN, CAPTIONS_ATTACH_BULLPUPSHOTGUN, CAPTIONS_ATTACH_SNIPERRIFLE, CAPTIONS_ATTACH_HEAVYSNIPER, CAPTIONS_ATTACH_GRENADELAUNCHER, CAPTIONS_ATTACH_BULLPUPRIFLE, CAPTIONS_ATTACH_GUSENBERG, CAPTIONS_ATTACH_HEAVYSHOTGUN, CAPTIONS_ATTACH_MARKSMANRIFLE, CAPTIONS_ATTACH_SNSPISTOL, CAPTIONS_ATTACH_SPECIALCARBINE, CAPTIONS_ATTACH_VINTAGEPISTOL, CAPTIONS_ATTACH_COMBATPDW, CAPTIONS_ATTACH_MACHINEPISTOL, CAPTIONS_ATTACH_SWITCHBLADE, CAPTIONS_ATTACH_REVOLVER, CAPTIONS_ATTACH_COMPACTRIFLE, CAPTIONS_ATTACH_MINISMG, CAPTIONS_ATTACH_PISTOLMK2, CAPTIONS_ATTACH_SMGMK2, CAPTIONS_ATTACH_ASSAULTRIFLEMK2, CAPTIONS_ATTACH_CARBINERIFLEMK2, CAPTIONS_ATTACH_COMBATMGMK2, CAPTIONS_ATTACH_HEAVYSNIPERMK2, CAPTIONS_ATTACH_SNSPISTOLMK2, CAPTIONS_ATTACH_REVOLVERMK2, CAPTIONS_ATTACH_SPECIALCARBINEMK2, CAPTIONS_ATTACH_BULLPUPMK2, CAPTIONS_ATTACH_PUMPSHOTGUNMK2, CAPTIONS_ATTACH_MARKSMANRIFLEMK2 };
const std::vector<std::string> VOV_WEAPONMOD_VALUES[] = { VALUES_ATTACH_PISTOL, VALUES_ATTACH_HEAVYPISTOL, VALUES_ATTACH_COMBATPISTOL, VALUES_ATTACH_APPISTOL, VALUES_ATTACH_PISTOL50, VALUES_ATTACH_MICROSMG, VALUES_ATTACH_SMG, VALUES_ATTACH_ASSAULTSMG, VALUES_ATTACH_ASSAULTRIFLE, VALUES_ATTACH_CARBINERIFLE, VALUES_ATTACH_ADVANCEDRIFLE, VALUES_ATTACH_MG, VALUES_ATTACH_COMBATMG, VALUES_ATTACH_SAWNOFF, VALUES_ATTACH_PUMPSHOTGUN, VALUES_ATTACH_ASSAULTSHOTGUN, VALUES_ATTACH_BULLPUPSHOTGUN, VALUES_ATTACH_SNIPERRIFLE, VALUES_ATTACH_HEAVYSNIPER, VALUES_ATTACH_GRENADELAUNCHER, VALUES_ATTACH_BULLPUPRIFLE, VALUES_ATTACH_GUSENBERG, VALUES_ATTACH_HEAVYSHOTGUN, VALUES_ATTACH_MARKSMANRIFLE, VALUES_ATTACH_SNSPISTOL, VALUES_ATTACH_SPECIALCARBINE, VALUES_ATTACH_VINTAGEPISTOL, VALUES_ATTACH_COMBATPDW, VALUES_ATTACH_MACHINEPISTOL, VALUES_ATTACH_SWITCHBLADE, VALUES_ATTACH_REVOLVER, VALUES_ATTACH_COMPACTRIFLE, VALUES_ATTACH_MINISMG, VALUES_ATTACH_PISTOLMK2, VALUES_ATTACH_SMGMK2, VALUES_ATTACH_ASSAULTRIFLEMK2, VALUES_ATTACH_CARBINERIFLEMK2, VALUES_ATTACH_COMBATMGMK2, VALUES_ATTACH_HEAVYSNIPERMK2, VALUES_ATTACH_SNSPISTOLMK2, VALUES_ATTACH_REVOLVERMK2, VALUES_ATTACH_SPECIALCARBINEMK2, VALUES_ATTACH_BULLPUPMK2, VALUES_ATTACH_PUMPSHOTGUNMK2, VALUES_ATTACH_MARKSMANRIFLEMK2 };

//MK2 weapons 
const std::vector<char*> MK2_WEAPONS{"WEAPON_PISTOL_MK2", "WEAPON_SNSPISTOL_MK2", "WEAPON_REVOLVER_MK2", "WEAPON_SMG_MK2", "WEAPON_COMBATMG_MK2", "WEAPON_ASSAULTRIFLE_MK2", "WEAPON_BULLPUPRIFLE_MK2", "WEAPON_CARBINERIFLE_MK2", "WEAPON_SPECIALCARBINE_MK2", "WEAPON_PUMPSHOTGUN_MK2", "WEAPON_HEAVYSNIPER_MK2", "WEAPON_MARKSMANRIFLE_MK2"};
const std::vector<char*> MK2_WEAPONS_LIVERY_COMP{"COMPONENT_PISTOL_MK2_CAMO", "COMPONENT_SNSPISTOL_MK2_CAMO", "COMPONENT_REVOLVER_MK2_CAMO", "COMPONENT_SMG_MK2_CAMO", "COMPONENT_COMBATMG_MK2_CAMO", "COMPONENT_ASSAULTRIFLE_MK2_CAMO", "COMPONENT_BULLPUPRIFLE_MK2_CAMO", "COMPONENT_CARBINERIFLE_MK2_CAMO", "COMPONENT_SPECIALCARBINE_MK2_CAMO", "COMPONENT_PUMPSHOTGUN_MK2_CAMO", "COMPONENT_HEAVYSNIPER_MK2_CAMO", "COMPONENT_MARKSMANRIFLE_MK2_CAMO" };


//Weapon damage modifier list
const std::vector<std::string> WEAP_DMG_CAPTIONS{"1.0x", "1.5x", "2.0x", "3.0x", "5.0x", "10.0x", "50.0x", "100.0x", "1000.0x"};
const std::vector<float> WEAP_DMG_FLOAT{1.0, 1.5, 2.0, 3.0, 5.0, 10.0, 50.0, 100.0, 1000.0};

const int PARACHUTE_ID = 0xFBAB5776;

const int TOTAL_WEAPONS_COUNT = 81;
const int TOTAL_WEAPONS_SLOTS = 80;
const int MAX_MOD_SLOTS = 15; 

extern bool featureNightVision;
extern bool featureThermalVision;

bool process_weapon_menu();

bool process_give_melee();
bool do_give_weapon(std::string modelName);
bool process_weaponlist_menu();

void reset_weapon_globals();

void update_weapon_features(BOOL bPlayerExists, Player player);

void onchange_cop_armed_index(int value, SelectFromListMenuItem* source);

void onchange_chance_police_calling_index(int value, SelectFromListMenuItem* source);

void onchange_chance_attacking_you_index(int value, SelectFromListMenuItem* source);

void onchange_sniper_vision_modifier(int value, SelectFromListMenuItem* source);

void onchange_cop_alarm_index(int value, SelectFromListMenuItem* source);

void add_weapon_feature_enablements2(std::vector<StringPairSettingDBRow>* results);

void update_vehicle_guns();

void save_player_weapons();

void give_all_weapons_hotkey();

void sniper_vision_toggle();

void restore_player_weapons();

bool is_weapon_equipped(std::vector<int> extras);

void set_weapon_equipped(bool equipped, std::vector<int> extras);

bool is_weaponmod_equipped(std::vector<int> extras);

void set_weaponmod_equipped(bool equipped, std::vector<int> extras);

void give_weapon_clip(MenuItem<int> choice);

void fill_weapon_ammo(MenuItem<int> choice);

void onconfirm_open_tint_menu(MenuItem<int> choice);

//Weapon mod menu

bool process_weapon_mod_menu_tint();

bool onconfirm_weapon_mod_menu_tint(MenuItem<int> choice);

void add_weapon_feature_enablements(std::vector<FeatureEnabledLocalDefinition>* results);

bool weapon_reequip_interrupt();

void onhighlight_weapon_mod_menu_tint_colour(MenuItem<int> choice);

bool onconfirm_weapon_mod_menu_tint_colour(MenuItem<int> choice);

void onconfirm_open_tint_menu_colour(MenuItem<int> choice);

// weapon damage modifier
void onchange_weap_dmg_modifier(int value, SelectFromListMenuItem* source);

void add_weapons_generic_settings(std::vector<StringPairSettingDBRow>* results);

void handle_generic_settings_weapons(std::vector<StringPairSettingDBRow>* settings);
