/*
Some of this code began its life as a part of GTA V SCRIPT HOOK SDK.
http://dev-c.com
(C) Alexander Blade 2015

It is now part of the Enhanced Native Trainer project.
https://github.com/gtav-ent/GTAV-EnhancedNativeTrainer
(C) Sondai SMith and fellow contributors 2015
*/

#pragma once

#include "..\..\inc\natives.h"
#include "..\..\inc\types.h"
#include "..\..\inc\enums.h"
#include "..\..\inc\main.h"
#include "..\ui_support\menu_functions.h"
#include "..\storage\database.h"

const std::vector<std::string> MENU_WEAPON_CATEGORIES{"Melee", "Handguns", "Submachine Guns", "Assault Rifles", "Shotguns", "Sniper Rifles", "Heavy Weapons", "Thrown Weapons"};

// Count: 19
const std::vector<std::string> CAPTIONS_MELEE{ "WT_KNIFE", "WT_NGTSTK", "WT_HAMMER", "WT_BAT", "WT_BALL", "WT_DIGI", "WT_GOLFCLUB", "WT_CROWBAR", "WT_BOTTLE", "WT_DAGGER", "WT_HATCHET", "WT_KNUCKLE", "WT_MACHETE", "WT_FLASHLIGHT", "WT_SWBLADE", "WT_BATTLEAXE", "WT_WRENCH", "WT_POOLCUE", "WT_SHATCHET" };
const std::vector<std::string> VALUES_MELEE{ "WEAPON_KNIFE", "WEAPON_NIGHTSTICK", "WEAPON_HAMMER", "WEAPON_BAT", "WEAPON_BALL", "WEAPON_DIGISCANNER", "WEAPON_GOLFCLUB", "WEAPON_CROWBAR", "WEAPON_BOTTLE", "WEAPON_DAGGER", "WEAPON_HATCHET", "WEAPON_KNUCKLE", "WEAPON_MACHETE", "WEAPON_FLASHLIGHT", "WEAPON_SWITCHBLADE", "WEAPON_BATTLEAXE", "WEAPON_WRENCH", "WEAPON_POOLCUE", "WEAPON_STONE_HATCHET" };
// Count: 17
const std::vector<std::string> CAPTIONS_HANDGUN{ "WT_PIST", "WT_PIST2", "WT_PIST_CBT", "WT_PIST_AP", "WT_PIST_50", "WT_SNSPISTOL", "WT_SNSPISTOL2", "WT_HEAVYPSTL", "WT_VPISTOL", "WT_STUN", "WT_FLAREGUN", "WT_MKPISTOL", "WT_REVOLVER", "WT_REVOLVER2", "WT_REV_DA", "WT_RAYPISTOL", "WT_CERPST", "WT_REV_NV" };
const std::vector<std::string> VALUES_HANDGUN{ "WEAPON_PISTOL", "WEAPON_PISTOL_MK2", "WEAPON_COMBATPISTOL", "WEAPON_APPISTOL", "WEAPON_PISTOL50", "WEAPON_SNSPISTOL", "WEAPON_SNSPISTOL_MK2", "WEAPON_HEAVYPISTOL", "WEAPON_VINTAGEPISTOL", "WEAPON_STUNGUN", "WEAPON_FLAREGUN", "WEAPON_MARKSMANPISTOL", "WEAPON_REVOLVER", "WEAPON_REVOLVER_MK2", "WEAPON_DOUBLEACTION", "WEAPON_RAYPISTOL", "WEAPON_CERAMICPISTOL", "WEAPON_NAVYREVOLVER" };
// Count: 10
const std::vector<std::string> CAPTIONS_SUBMACHINE{ "WT_SMG_MCR", "WT_SMG", "WT_SMG2", "WT_SMG_ASL", "WT_MG", "WT_MG_CBT", "WT_MG_CBT2", "WT_GUSENBERG", "WT_COMBATPDW", "WT_MCHPIST", "WT_MINISMG" };
const std::vector<std::string> VALUES_SUBMACHINE{ "WEAPON_MICROSMG", "WEAPON_SMG", "WEAPON_SMG_MK2", "WEAPON_ASSAULTSMG", "WEAPON_MG", "WEAPON_COMBATMG", "WEAPON_COMBATMG_MK2", "WEAPON_GUSENBERG", "WEAPON_COMBATPDW", "WEAPON_MACHINEPISTOL", "WEAPON_MINISMG" };
// Count: 8
const std::vector<std::string> CAPTIONS_ASSAULT{ "WT_RIFLE_ASL", "WT_RIFLE_ASL2", "WT_BULLRIFLE2", "WT_RIFLE_CBN", "WT_RIFLE_CBN2", "WT_RIFLE_ADV", "WT_RIFLE_SCBN", "WT_SPCARBINE2", "WT_BULLRIFLE", "WT_CMPRIFLE", "WT_RAYCARBINE" };
const std::vector<std::string> VALUES_ASSAULT{ "WEAPON_ASSAULTRIFLE", "WEAPON_ASSAULTRIFLE_MK2", "WEAPON_BULLPUPRIFLE_MK2", "WEAPON_CARBINERIFLE", "WEAPON_CARBINERIFLE_MK2", "WEAPON_ADVANCEDRIFLE", "WEAPON_SPECIALCARBINE", "WEAPON_SPECIALCARBINE_MK2", "WEAPON_BULLPUPRIFLE", "WEAPON_COMPACTRIFLE", "WEAPON_RAYCARBINE" };
// Count: 9
const std::vector<std::string> CAPTIONS_SHOTGUN{ "WT_SG_PMP", "WT_SG_PMP2", "WT_SG_SOF", "WT_SG_BLP", "WT_SG_ASL", "WT_MUSKET", "WT_HVYSHOT", "WT_DBSHGN", "WT_AUTOSHGN" };
const std::vector<std::string> VALUES_SHOTGUN{ "WEAPON_PUMPSHOTGUN", "WEAPON_PUMPSHOTGUN_MK2", "WEAPON_SAWNOFFSHOTGUN", "WEAPON_BULLPUPSHOTGUN", "WEAPON_ASSAULTSHOTGUN", "WEAPON_MUSKET", "WEAPON_HEAVYSHOTGUN", "WEAPON_DBSHOTGUN", "WEAPON_AUTOSHOTGUN" };
// Count: 3
const std::vector<std::string> CAPTIONS_SNIPER{ "WT_SNIP_RIF", "WT_SNIP_HVY", "WT_SNIP_HVY2", "WT_MKRIFLE", "WT_MKRIFLE2" };
const std::vector<std::string> VALUES_SNIPER{ "WEAPON_SNIPERRIFLE", "WEAPON_HEAVYSNIPER", "WEAPON_HEAVYSNIPER_MK2", "WEAPON_MARKSMANRIFLE", "WEAPON_MARKSMANRIFLE_MK2" };
// Count: 7
const std::vector<std::string> CAPTIONS_HEAVY{ "WT_GL", "WT_RPG", "WT_MINIGUN", "WT_FIREWRK", "WT_RAILGUN", "WT_HOMLNCH", "WT_CMPGL", "WT_RAYMINIGUN" };
const std::vector<std::string> VALUES_HEAVY{ "WEAPON_GRENADELAUNCHER", "WEAPON_RPG", "WEAPON_MINIGUN", "WEAPON_FIREWORK", "WEAPON_RAILGUN", "WEAPON_HOMINGLAUNCHER", "WEAPON_COMPACTLAUNCHER", "WEAPON_RAYMINIGUN" };
// Count: 10
const std::vector<std::string> CAPTIONS_THROWN{ "WT_GNADE", "WT_GNADE_STK", "WT_PRXMINE", "WT_BZGAS", "WT_MOLOTOV", "WT_FIRE", "WT_PETROL", "WT_SNWBALL", "WT_FLARE", "WT_PIPEBOMB"/*, "BZ Gas"*/, "WT_HAZARDCAN" };
const std::vector<std::string> VALUES_THROWN{ "WEAPON_GRENADE", "WEAPON_STICKYBOMB", "WEAPON_PROXMINE", "WEAPON_SMOKEGRENADE", "WEAPON_MOLOTOV", "WEAPON_FIREEXTINGUISHER", "WEAPON_PETROLCAN", "WEAPON_SNOWBALL", "WEAPON_FLARE", "WEAPON_PIPEBOMB"/*, "WEAPON_BZGAS"*/, "WEAPON_HAZARDCAN" };


const std::vector<std::string> VOV_WEAPON_CAPTIONS[] = {CAPTIONS_MELEE, CAPTIONS_HANDGUN, CAPTIONS_SUBMACHINE, CAPTIONS_ASSAULT, CAPTIONS_SHOTGUN, CAPTIONS_SNIPER, CAPTIONS_HEAVY, CAPTIONS_THROWN};
const std::vector<std::string> VOV_WEAPON_VALUES[] = {VALUES_MELEE, VALUES_HANDGUN, VALUES_SUBMACHINE, VALUES_ASSAULT, VALUES_SHOTGUN, VALUES_SNIPER, VALUES_HEAVY, VALUES_THROWN};

//Weapon tints
const std::vector<std::string> CAPTIONS_TINT{"Normal", "Green", "Gold", "Pink", "Army", "LSPD", "Orange", "Platinum"};
const std::vector<int> VALUES_TINT{0, 1, 2, 3, 4, 5, 6, 7};

//Weapon tints for MK2 weapons
const std::vector<std::string> CAPTIONS_TINT_MK2{ "Classic Black", "Classic Gray", "Classic Two-Tone", "Classic White", "Classic Beige", "Classic Green", "Classic Blue", "Classic Earth", "Classic Brown & Black", "Red Contrast", "Blue Contrast", "Yellow Contrast", "Orange Contrast", "Bold Pink", "Bold Purple & Yellow", "Bold Orange", "Bold Green & Purple", "Bold Red Features", "Bold Green Features", "Bold Cyan Features", "Bold Yellow Features", "Bold Red & White", "Bold Blue & White", "Metallic Gold", "Metallic Platinum", "Metallic Gray & Lilca", "Metallic Purple & Lime", "Metallic Red", "Metallic Green", "Metallic Blue", "Metallic White & Aqua", "Metallic Red & Yellow" };
const std::vector<int> VALUES_TINT_MK2{ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31 };

//Pistols
const std::vector<std::string> CAPTIONS_ATTACH_PISTOL{"WCT_CLIP1", "WCT_CLIP2", "WCT_FLASH", "WCT_SUPP", "WCT_VAR_GOLD"};
const std::vector<std::string> VALUES_ATTACH_PISTOL{"COMPONENT_PISTOL_CLIP_01", "COMPONENT_PISTOL_CLIP_02", "COMPONENT_AT_PI_FLSH", "COMPONENT_AT_PI_SUPP_02", "COMPONENT_PISTOL_VARMOD_LUXE"};

const std::vector<std::string> CAPTIONS_ATTACH_COMBATPISTOL{"WCT_CLIP1", "WCT_CLIP2", "WCT_FLASH", "WCT_SUPP", "WCT_VAR_GOLD"};
const std::vector<std::string> VALUES_ATTACH_COMBATPISTOL{"COMPONENT_COMBATPISTOL_CLIP_01", "COMPONENT_COMBATPISTOL_CLIP_02", "COMPONENT_AT_PI_FLSH", "COMPONENT_AT_PI_SUPP", "COMPONENT_COMBATPISTOL_VARMOD_LOWRIDER"};

const std::vector<std::string> CAPTIONS_ATTACH_APPISTOL{"WCT_CLIP1", "WCT_CLIP2", "WCT_FLASH", "WCT_SUPP", "WCT_VAR_METAL"};
const std::vector<std::string> VALUES_ATTACH_APPISTOL{"COMPONENT_APPISTOL_CLIP_01", "COMPONENT_APPISTOL_CLIP_02", "COMPONENT_AT_PI_FLSH", "COMPONENT_AT_PI_SUPP", "COMPONENT_APPISTOL_VARMOD_LUXE"};

const std::vector<std::string> CAPTIONS_ATTACH_PISTOL50{"WCT_CLIP1", "WCT_CLIP2", "WCT_FLASH", "WCT_SUPP", "WCT_VAR_SIL"};
const std::vector<std::string> VALUES_ATTACH_PISTOL50{"COMPONENT_PISTOL50_CLIP_01", "COMPONENT_PISTOL50_CLIP_02", "COMPONENT_AT_PI_FLSH", "COMPONENT_AT_AR_SUPP_02", "COMPONENT_PISTOL50_VARMOD_LUXE"};

const std::vector<std::string> CAPTIONS_ATTACH_CERAMIC_PISTOL{"WCT_CLIP1", "WCT_CLIP2", "WCT_SUPP"};
const std::vector<std::string> VALUES_ATTACH_CERAMIC_PISTOL{"COMPONENT_CERAMICPISTOL_CLIP_01", "COMPONENT_CERAMICPISTOL_CLIP_02", "COMPONENT_CERAMICPISTOL_SUPP"};

//SMGs
const std::vector<std::string> CAPTIONS_ATTACH_MICROSMG{"WCT_CLIP1", "WCT_CLIP2", "WCT_FLASH", "WCT_SCOPE_MAC", "WCT_SUPP", "WCT_VAR_GOLD"};
const std::vector<std::string> VALUES_ATTACH_MICROSMG{"COMPONENT_MICROSMG_CLIP_01", "COMPONENT_MICROSMG_CLIP_02", "COMPONENT_AT_PI_FLSH", "COMPONENT_AT_SCOPE_MACRO", "COMPONENT_AT_AR_SUPP_02", "COMPONENT_MICROSMG_VARMOD_LUXE"};

const std::vector<std::string> CAPTIONS_ATTACH_SMG{"WCT_CLIP1", "WCT_CLIP2", "WCT_CLIP_DRM", "WCT_FLASH", "WCT_SCOPE_MAC", "WCT_SUPP", "WCT_VAR_GOLD"};
const std::vector<std::string> VALUES_ATTACH_SMG{"COMPONENT_SMG_CLIP_01", "COMPONENT_SMG_CLIP_02", "COMPONENT_SMG_CLIP_03", "COMPONENT_AT_AR_FLSH", "COMPONENT_AT_SCOPE_MACRO_02", "COMPONENT_AT_PI_SUPP", "COMPONENT_SMG_VARMOD_LUXE"};

const std::vector<std::string> CAPTIONS_ATTACH_ASSAULTSMG{"WCT_CLIP1", "WCT_CLIP2", "WCT_FLASH", "WCT_SCOPE_MAC", "WCT_SUPP", "WCT_VAR_GOLD"};
const std::vector<std::string> VALUES_ATTACH_ASSAULTSMG{"COMPONENT_ASSAULTSMG_CLIP_01", "COMPONENT_ASSAULTSMG_CLIP_02", "COMPONENT_AT_AR_FLSH", "COMPONENT_AT_SCOPE_MACRO", "COMPONENT_AT_AR_SUPP_02", "COMPONENT_ASSAULTSMG_VARMOD_LOWRIDER"};

//Rifles
const std::vector<std::string> CAPTIONS_ATTACH_ASSAULTRIFLE{"WCT_CLIP1", "WCT_CLIP2", "WCT_CLIP_DRM", "WCT_FLASH", "WCT_SCOPE_MAC", "WCT_SUPP", "WCT_GRIP", "WCT_VAR_GOLD"};
const std::vector<std::string> VALUES_ATTACH_ASSAULTRIFLE{"COMPONENT_ASSAULTRIFLE_CLIP_01", "COMPONENT_ASSAULTRIFLE_CLIP_02", "COMPONENT_ASSAULTRIFLE_CLIP_03", "COMPONENT_AT_AR_FLSH", "COMPONENT_AT_SCOPE_MACRO", "COMPONENT_AT_AR_SUPP_02", "COMPONENT_AT_AR_AFGRIP", "COMPONENT_ASSAULTRIFLE_VARMOD_LUXE"};

const std::vector<std::string> CAPTIONS_ATTACH_CARBINERIFLE{"WCT_CLIP1", "WCT_CLIP2", "WCT_CLIP_DRM", "WCT_FLASH", "WCT_SCOPE_MAC", "WCT_SUPP", "WCT_GRIP", "WCT_VAR_GOLD"};
const std::vector<std::string> VALUES_ATTACH_CARBINERIFLE{"COMPONENT_CARBINERIFLE_CLIP_01", "COMPONENT_CARBINERIFLE_CLIP_02", "COMPONENT_CARBINERIFLE_CLIP_03", "COMPONENT_AT_AR_FLSH", "COMPONENT_AT_SCOPE_MEDIUM", "COMPONENT_AT_AR_SUPP", "COMPONENT_AT_AR_AFGRIP", "COMPONENT_CARBINERIFLE_VARMOD_LUXE"};

const std::vector<std::string> CAPTIONS_ATTACH_ADVANCEDRIFLE{"WCT_CLIP1", "WCT_CLIP2", "WCT_FLASH", "WCT_SCOPE_MAC", "WCT_SUPP", "WCT_VAR_METAL"};
const std::vector<std::string> VALUES_ATTACH_ADVANCEDRIFLE{"COMPONENT_ADVANCEDRIFLE_CLIP_01", "COMPONENT_ADVANCEDRIFLE_CLIP_02", "COMPONENT_AT_AR_FLSH", "COMPONENT_AT_SCOPE_SMALL", "COMPONENT_AT_AR_SUPP", "COMPONENT_ADVANCEDRIFLE_VARMOD_LUXE"};

//Machine Guns
const std::vector<std::string> CAPTIONS_ATTACH_MG{"WCT_CLIP1", "WCT_CLIP2", "WCT_SCOPE_MAC", "WCT_VAR_GOLD"};
const std::vector<std::string> VALUES_ATTACH_MG{"COMPONENT_MG_CLIP_01", "COMPONENT_MG_CLIP_02", "COMPONENT_AT_SCOPE_SMALL_02", "COMPONENT_MG_VARMOD_LOWRIDER"};

const std::vector<std::string> CAPTIONS_ATTACH_COMBATMG{"WCT_CLIP1", "WCT_CLIP2", "WCT_SCOPE_MAC", "WCT_GRIP", "WCT_VAR_ETCHM"};
const std::vector<std::string> VALUES_ATTACH_COMBATMG{"COMPONENT_COMBATMG_CLIP_01", "COMPONENT_COMBATMG_CLIP_02", "COMPONENT_AT_SCOPE_MEDIUM", "COMPONENT_AT_AR_AFGRIP", "COMPONENT_COMBATMG_VARMOD_LOWRIDER"};

//Shotguns
const std::vector<std::string> CAPTIONS_ATTACH_PUMPSHOTGUN{"WCT_FLASH", "WCT_SUPP", "WCT_VAR_GOLD"};
const std::vector<std::string> VALUES_ATTACH_PUMPSHOTGUN{"COMPONENT_AT_AR_FLSH", "COMPONENT_AT_SR_SUPP", "COMPONENT_PUMPSHOTGUN_VARMOD_LOWRIDER"};

const std::vector<std::string> CAPTIONS_ATTACH_SAWNOFF{"WCT_VAR_METAL"};
const std::vector<std::string> VALUES_ATTACH_SAWNOFF{"COMPONENT_SAWNOFFSHOTGUN_VARMOD_LUXE"};

const std::vector<std::string> CAPTIONS_ATTACH_ASSAULTSHOTGUN{"WCT_CLIP1", "WCT_CLIP2", "WCT_FLASH", "WCT_SUPP", "WCT_GRIP"};
const std::vector<std::string> VALUES_ATTACH_ASSAULTSHOTGUN{"COMPONENT_ASSAULTSHOTGUN_CLIP_01", "COMPONENT_ASSAULTSHOTGUN_CLIP_02", "COMPONENT_AT_AR_FLSH", "COMPONENT_AT_AR_SUPP", "COMPONENT_AT_AR_AFGRIP"};

const std::vector<std::string> CAPTIONS_ATTACH_BULLPUPSHOTGUN{"WCT_FLASH", "WCT_SUPP", "WCT_GRIP"};
const std::vector<std::string> VALUES_ATTACH_BULLPUPSHOTGUN{"COMPONENT_AT_AR_FLSH", "COMPONENT_AT_AR_SUPP_02", "COMPONENT_AT_AR_AFGRIP"};

//Sniper Rifles
const std::vector<std::string> CAPTIONS_ATTACH_SNIPERRIFLE{"WCT_CLIP1", "WCT_SUPP", "WCT_SCOPE_LRG", "WCT_SCOPE_MAX", "WCT_VAR_WOOD"};
const std::vector<std::string> VALUES_ATTACH_SNIPERRIFLE{"COMPONENT_SNIPERRIFLE_CLIP_01", "COMPONENT_AT_AR_SUPP_02", "COMPONENT_AT_SCOPE_LARGE", "COMPONENT_AT_SCOPE_MAX", "COMPONENT_SNIPERRIFLE_VARMOD_LUXE"};

const std::vector<std::string> CAPTIONS_ATTACH_HEAVYSNIPER{"WCT_SCOPE_LRG", "WCT_SCOPE_MAX"}; // "WCT_CLIP1", 
const std::vector<std::string> VALUES_ATTACH_HEAVYSNIPER{"COMPONENT_AT_SCOPE_LARGE", "COMPONENT_AT_SCOPE_MAX"}; // "COMPONENT_HEAVYSNIPER_CLIP_01", 

//Heavy Weapons
const std::vector<std::string> CAPTIONS_ATTACH_GRENADELAUNCHER{"WCT_CLIP1", "WCT_FLASH", "WCT_GRIP", "WCT_SCOPE_MAC"};
const std::vector<std::string> VALUES_ATTACH_GRENADELAUNCHER{"COMPONENT_GRENADELAUNCHER_CLIP_01", "COMPONENT_AT_AR_FLSH", "COMPONENT_AT_AR_AFGRIP", "COMPONENT_AT_SCOPE_SMALL"};

//DLC Weapons
const std::vector<std::string> CAPTIONS_ATTACH_BULLPUPRIFLE{"WCT_CLIP1", "WCT_CLIP2", "WCT_FLASH", "WCT_SCOPE_MAC", "WCT_SUPP", "WCT_GRIP", "WCT_VAR_METAL"};
const std::vector<std::string> VALUES_ATTACH_BULLPUPRIFLE{"COMPONENT_BULLPUPRIFLE_CLIP_01", "COMPONENT_BULLPUPRIFLE_CLIP_02", "COMPONENT_AT_AR_FLSH", "COMPONENT_AT_SCOPE_SMALL", "COMPONENT_AT_AR_SUPP", "COMPONENT_AT_AR_AFGRIP", "COMPONENT_BULLPUPRIFLE_VARMOD_LOW"};

const std::vector<std::string> CAPTIONS_ATTACH_COMBATPDW{"WCT_CLIP1", "WCT_CLIP2", "WCT_CLIP_DRM", "WCT_FLASH", "WCT_GRIP", "WCT_SCOPE_SML"};
const std::vector<std::string> VALUES_ATTACH_COMBATPDW{"COMPONENT_COMBATPDW_CLIP_01", "COMPONENT_COMBATPDW_CLIP_02", "COMPONENT_COMBATPDW_CLIP_03", "COMPONENT_AT_AR_FLSH", "COMPONENT_AT_AR_AFGRIP", "COMPONENT_AT_SCOPE_SMALL"};

const std::vector<std::string> CAPTIONS_ATTACH_COMPACTRIFLE{"WCT_CLIP1", "WCT_CLIP2", "WCT_CLIP_DRM"};
const std::vector<std::string> VALUES_ATTACH_COMPACTRIFLE{"COMPONENT_COMPACTRIFLE_CLIP_01", "COMPONENT_COMPACTRIFLE_CLIP_02", "COMPONENT_COMPACTRIFLE_CLIP_03"};

const std::vector<std::string> CAPTIONS_ATTACH_GUSENBERG{"WCT_CLIP1", "WCT_CLIP2"};
const std::vector<std::string> VALUES_ATTACH_GUSENBERG{"COMPONENT_GUSENBERG_CLIP_01", "COMPONENT_GUSENBERG_CLIP_02"};

const std::vector<std::string> CAPTIONS_ATTACH_HEAVYPISTOL{"WCT_CLIP1", "WCT_CLIP2", "WCT_FLASH", "WCT_SUPP", "WCT_VAR_WOOD"};
const std::vector<std::string> VALUES_ATTACH_HEAVYPISTOL{"COMPONENT_HEAVYPISTOL_CLIP_01", "COMPONENT_HEAVYPISTOL_CLIP_02", "COMPONENT_AT_PI_FLSH", "COMPONENT_AT_PI_SUPP", "COMPONENT_HEAVYPISTOL_VARMOD_LUXE"};

const std::vector<std::string> CAPTIONS_ATTACH_HEAVYSHOTGUN{"WCT_CLIP1", "WCT_CLIP2", "WCT_CLIP_DRM", "WCT_FLASH", "WCT_SUPP", "WCT_GRIP"};
const std::vector<std::string> VALUES_ATTACH_HEAVYSHOTGUN{"COMPONENT_HEAVYSHOTGUN_CLIP_01", "COMPONENT_HEAVYSHOTGUN_CLIP_02", "COMPONENT_HEAVYSHOTGUN_CLIP_03", "COMPONENT_AT_AR_FLSH", "COMPONENT_AT_AR_SUPP_02", "COMPONENT_AT_AR_AFGRIP"};

const std::vector<std::string> CAPTIONS_ATTACH_KNUCKLES{"WCT_KNUCK_01", "WCT_KNUCK_02", "WCT_KNUCK_BG", "WCT_KNUCK_DLR", "WCT_KNUCK_DMD", "WCT_KNUCK_HT", "WCT_KNUCK_LV", "WCT_KNUCK_PC", "WCT_KNUCK_SLG", "WCT_KNUCK_VG"};
const std::vector<std::string> VALUES_ATTACH_KNUCKLES{"COMPONENT_KNUCKLE_VARMOD_BASE", "COMPONENT_KNUCKLE_VARMOD_PIMP", "COMPONENT_KNUCKLE_VARMOD_BALLAS", "COMPONENT_KNUCKLE_VARMOD_DOLLAR", "COMPONENT_KNUCKLE_VARMOD_DIAMOND", "COMPONENT_KNUCKLE_VARMOD_HATE", "COMPONENT_KNUCKLE_VARMOD_LOVE", "COMPONENT_KNUCKLE_VARMOD_PLAYER", "COMPONENT_KNUCKLE_VARMOD_KING", "COMPONENT_KNUCKLE_VARMOD_VAGOS"};

const std::vector<std::string> CAPTIONS_ATTACH_MACHINEPISTOL{"WCT_CLIP1", "WCT_CLIP2", "WCT_CLIP_DRM", "WCT_SUPP"};
const std::vector<std::string> VALUES_ATTACH_MACHINEPISTOL{"COMPONENT_MACHINEPISTOL_CLIP_01", "COMPONENT_MACHINEPISTOL_CLIP_02", "COMPONENT_MACHINEPISTOL_CLIP_03", "COMPONENT_AT_PI_SUPP"};

const std::vector<std::string> CAPTIONS_ATTACH_MARKSMANRIFLE{"WCT_CLIP1", "WCT_CLIP2", /*"WCT_SCOPE_LRG", */"WCT_FLASH", "WCT_SUPP", "WCT_GRIP", "WCT_VAR_GOLD"};
const std::vector<std::string> VALUES_ATTACH_MARKSMANRIFLE{"COMPONENT_MARKSMANRIFLE_CLIP_01", "COMPONENT_MARKSMANRIFLE_CLIP_02", /*"COMPONENT_AT_SCOPE_LARGE_FIXED_ZOOM", */"COMPONENT_AT_AR_FLSH", "COMPONENT_AT_AR_SUPP", "COMPONENT_AT_AR_AFGRIP", "COMPONENT_MARKSMANRIFLE_VARMOD_LUXE"};

const std::vector<std::string> CAPTIONS_ATTACH_MINISMG{"WCT_CLIP1", "WCT_CLIP2"};
const std::vector<std::string> VALUES_ATTACH_MINISMG{"COMPONENT_MINISMG_CLIP_01", "COMPONENT_MINISMG_CLIP_02"};

const std::vector<std::string> CAPTIONS_ATTACH_REVOLVER{"WCT_REV_VARB", "WCT_REV_VARG"}; // , "WCT_CLIP1"
const std::vector<std::string> VALUES_ATTACH_REVOLVER{"COMPONENT_REVOLVER_VARMOD_BOSS", "COMPONENT_REVOLVER_VARMOD_GOON"}; // , "COMPONENT_REVOLVER_CLIP_01"

const std::vector<std::string> CAPTIONS_ATTACH_SNSPISTOL{"WCT_CLIP1", "WCT_CLIP2", "WCT_VAR_WOOD"};
const std::vector<std::string> VALUES_ATTACH_SNSPISTOL{"COMPONENT_SNSPISTOL_CLIP_01", "COMPONENT_SNSPISTOL_CLIP_02", "COMPONENT_SNSPISTOL_VARMOD_LOWRIDER"};

const std::vector<std::string> CAPTIONS_ATTACH_SPECIALCARBINE{"WCT_CLIP1", "WCT_CLIP2", "WCT_CLIP_DRM", "WCT_FLASH", "WCT_SCOPE_MAC", "WCT_SUPP", "WCT_GRIP", "WCT_VAR_ETCHM"};
const std::vector<std::string> VALUES_ATTACH_SPECIALCARBINE{"COMPONENT_SPECIALCARBINE_CLIP_01", "COMPONENT_SPECIALCARBINE_CLIP_02", "COMPONENT_SPECIALCARBINE_CLIP_03", "COMPONENT_AT_AR_FLSH", "COMPONENT_AT_SCOPE_MEDIUM", "COMPONENT_AT_AR_SUPP_02", "COMPONENT_AT_AR_AFGRIP", "COMPONENT_SPECIALCARBINE_VARMOD_LOWRIDER"};

const std::vector<std::string> CAPTIONS_ATTACH_SWITCHBLADE{"WCT_SB_BASE", "WCT_SB_VAR1", "WCT_SB_VAR2"};
const std::vector<std::string> VALUES_ATTACH_SWITCHBLADE{"COMPONENT_SWITCHBLADE_VARMOD_BASE", "COMPONENT_SWITCHBLADE_VARMOD_VAR1", "COMPONENT_SWITCHBLADE_VARMOD_VAR2"};

const std::vector<std::string> CAPTIONS_ATTACH_VINTAGEPISTOL{"WCT_CLIP1", "WCT_CLIP2", "WCT_SUPP"};
const std::vector<std::string> VALUES_ATTACH_VINTAGEPISTOL{"COMPONENT_VINTAGEPISTOL_CLIP_01", "COMPONENT_VINTAGEPISTOL_CLIP_02", "COMPONENT_AT_PI_SUPP"};

/*Gun Running DLC*/
const std::vector<std::string> CAPTIONS_ATTACH_PISTOLMK2{"WCT_CLIP1", "WCT_CLIP2", "WCT_CLIP_TR", "WCT_CLIP_INC", "WCT_CLIP_HP", "WCT_CLIP_FMJ", "WCT_SCOPE_PI", "WCT_FLASH", "WCT_SUPP", "WCT_COMP", "WCT_CAMO_1", "WCT_CAMO_2", "WCT_CAMO_3", "WCT_CAMO_4", "WCT_CAMO_5", "WCT_CAMO_6", "WCT_CAMO_7", "WCT_CAMO_8", "WCT_CAMO_9", "WCT_CAMO_10", "WCT_CAMO_IND", "WCT_CAMO_1", "WCT_CAMO_2", "WCT_CAMO_3", "WCT_CAMO_4", "WCT_CAMO_5", "WCT_CAMO_6", "WCT_CAMO_7", "WCT_CAMO_8", "WCT_CAMO_9", "WCT_CAMO_10", "WCT_CAMO_IND"};
const std::vector<std::string> VALUES_ATTACH_PISTOLMK2{"COMPONENT_PISTOL_MK2_CLIP_01", "COMPONENT_PISTOL_MK2_CLIP_02", "COMPONENT_PISTOL_MK2_CLIP_TRACER", "COMPONENT_PISTOL_MK2_CLIP_INCENDIARY", "COMPONENT_PISTOL_MK2_CLIP_HOLLOWPOINT", "COMPONENT_PISTOL_MK2_CLIP_FMJ", "COMPONENT_AT_PI_RAIL", "COMPONENT_AT_PI_FLSH_02", "COMPONENT_AT_PI_SUPP_02", "COMPONENT_AT_PI_COMP", "COMPONENT_PISTOL_MK2_CAMO", "COMPONENT_PISTOL_MK2_CAMO_02", "COMPONENT_PISTOL_MK2_CAMO_03", "COMPONENT_PISTOL_MK2_CAMO_04", "COMPONENT_PISTOL_MK2_CAMO_05", "COMPONENT_PISTOL_MK2_CAMO_06", "COMPONENT_PISTOL_MK2_CAMO_07", "COMPONENT_PISTOL_MK2_CAMO_08", "COMPONENT_PISTOL_MK2_CAMO_09", "COMPONENT_PISTOL_MK2_CAMO_10", "COMPONENT_PISTOL_MK2_CAMO_IND_01", "COMPONENT_PISTOL_MK2_CAMO_SLIDE", "COMPONENT_PISTOL_MK2_CAMO_02_SLIDE", "COMPONENT_PISTOL_MK2_CAMO_03_SLIDE", "COMPONENT_PISTOL_MK2_CAMO_04_SLIDE", "COMPONENT_PISTOL_MK2_CAMO_05_SLIDE", "COMPONENT_PISTOL_MK2_CAMO_06_SLIDE", "COMPONENT_PISTOL_MK2_CAMO_07_SLIDE", "COMPONENT_PISTOL_MK2_CAMO_08_SLIDE", "COMPONENT_PISTOL_MK2_CAMO_09_SLIDE", "COMPONENT_PISTOL_MK2_CAMO_10_SLIDE", "COMPONENT_PISTOL_MK2_CAMO_IND_01_SLIDE"};

const std::vector<std::string> CAPTIONS_ATTACH_SMGMK2{"WCT_CLIP1", "WCT_CLIP2", "WCT_CLIP_TR", "WCT_CLIP_INC", "WCT_CLIP_HP", "WCT_CLIP_FMJ", "WCT_FLASH", "WCT_HOLO", "WCT_SCOPE_MAC2", "WCT_SCOPE_SML2", "WCT_SUPP", "WCT_MUZZ1", "WCT_MUZZ2", "WCT_MUZZ3", "WCT_MUZZ4", "WCT_MUZZ5", "WCT_MUZZ6", "WCT_MUZZ7", "WCT_BARR", "WCT_BARR2", "WCT_CAMO_1", "WCT_CAMO_2", "WCT_CAMO_3", "WCT_CAMO_4", "WCT_CAMO_5", "WCT_CAMO_6", "WCT_CAMO_7", "WCT_CAMO_8", "WCT_CAMO_9", "WCT_CAMO_10", "WCT_CAMO_IND"};
const std::vector<std::string> VALUES_ATTACH_SMGMK2{"COMPONENT_SMG_MK2_CLIP_01", "COMPONENT_SMG_MK2_CLIP_02", "COMPONENT_SMG_MK2_CLIP_TRACER", "COMPONENT_SMG_MK2_CLIP_INCENDIARY", "COMPONENT_SMG_MK2_CLIP_HOLLOWPOINT", "COMPONENT_SMG_MK2_CLIP_FMJ", "COMPONENT_AT_AR_FLSH", "COMPONENT_AT_SIGHTS_SMG", "COMPONENT_AT_SCOPE_MACRO_02_SMG_MK2", "COMPONENT_AT_SCOPE_SMALL_SMG_MK2", "COMPONENT_AT_PI_SUPP", "COMPONENT_AT_MUZZLE_01", "COMPONENT_AT_MUZZLE_02", "COMPONENT_AT_MUZZLE_03", "COMPONENT_AT_MUZZLE_04", "COMPONENT_AT_MUZZLE_05", "COMPONENT_AT_MUZZLE_06", "COMPONENT_AT_MUZZLE_07", "COMPONENT_AT_SB_BARREL_01", "COMPONENT_AT_SB_BARREL_02", "COMPONENT_SMG_MK2_CAMO", "COMPONENT_SMG_MK2_CAMO_02", "COMPONENT_SMG_MK2_CAMO_03", "COMPONENT_SMG_MK2_CAMO_04", "COMPONENT_SMG_MK2_CAMO_05", "COMPONENT_SMG_MK2_CAMO_06", "COMPONENT_SMG_MK2_CAMO_07", "COMPONENT_SMG_MK2_CAMO_08", "COMPONENT_SMG_MK2_CAMO_09", "COMPONENT_SMG_MK2_CAMO_10", "COMPONENT_SMG_MK2_CAMO_IND_01"};

const std::vector<std::string> CAPTIONS_ATTACH_ASSAULTRIFLEMK2{"WCT_CLIP1", "WCT_CLIP2", "WCT_CLIP_TR", "WCT_CLIP_INC", "WCT_CLIP_AP", "WCT_CLIP_FMJ", "WCT_GRIP", "WCT_FLASH", "WCT_HOLO", "WCT_SCOPE_MAC2", "WCT_SCOPE_MED2", "WCT_SUPP", "WCT_MUZZ1", "WCT_MUZZ2", "WCT_MUZZ3", "WCT_MUZZ4", "WCT_MUZZ5", "WCT_MUZZ6", "WCT_MUZZ7", "WCT_BARR", "WCT_BARR2", "WCT_CAMO_1", "WCT_CAMO_2", "WCT_CAMO_3", "WCT_CAMO_4", "WCT_CAMO_5", "WCT_CAMO_6", "WCT_CAMO_7", "WCT_CAMO_8", "WCT_CAMO_9", "WCT_CAMO_10", "WCT_CAMO_IND"};
const std::vector<std::string> VALUES_ATTACH_ASSAULTRIFLEMK2{"COMPONENT_ASSAULTRIFLE_MK2_CLIP_01", "COMPONENT_ASSAULTRIFLE_MK2_CLIP_02", "COMPONENT_ASSAULTRIFLE_MK2_CLIP_TRACER", "COMPONENT_ASSAULTRIFLE_MK2_CLIP_INCENDIARY", "COMPONENT_ASSAULTRIFLE_MK2_CLIP_ARMORPIERCING", "COMPONENT_ASSAULTRIFLE_MK2_CLIP_FMJ", "COMPONENT_AT_AR_AFGRIP_02", "COMPONENT_AT_AR_FLSH", "COMPONENT_AT_SIGHTS", "COMPONENT_AT_SCOPE_MACRO_MK2", "COMPONENT_AT_SCOPE_MEDIUM_MK2", "COMPONENT_AT_AR_SUPP_02", "COMPONENT_AT_MUZZLE_01", "COMPONENT_AT_MUZZLE_02", "COMPONENT_AT_MUZZLE_03", "COMPONENT_AT_MUZZLE_04", "COMPONENT_AT_MUZZLE_05", "COMPONENT_AT_MUZZLE_06", "COMPONENT_AT_MUZZLE_07", "COMPONENT_AT_AR_BARREL_01", "COMPONENT_AT_AR_BARREL_02", "COMPONENT_ASSAULTRIFLE_MK2_CAMO", "COMPONENT_ASSAULTRIFLE_MK2_CAMO_02", "COMPONENT_ASSAULTRIFLE_MK2_CAMO_03", "COMPONENT_ASSAULTRIFLE_MK2_CAMO_04", "COMPONENT_ASSAULTRIFLE_MK2_CAMO_05", "COMPONENT_ASSAULTRIFLE_MK2_CAMO_06", "COMPONENT_ASSAULTRIFLE_MK2_CAMO_07", "COMPONENT_ASSAULTRIFLE_MK2_CAMO_08", "COMPONENT_ASSAULTRIFLE_MK2_CAMO_09", "COMPONENT_ASSAULTRIFLE_MK2_CAMO_10", "COMPONENT_ASSAULTRIFLE_MK2_CAMO_IND_01"};

const std::vector<std::string> CAPTIONS_ATTACH_CARBINERIFLEMK2{"WCT_CLIP1", "WCT_CLIP2", "WCT_CLIP_TR", "WCT_CLIP_INC", "WCT_CLIP_AP", "WCT_CLIP_FMJ", "WCT_GRIP", "WCT_FLASH", "WCT_HOLO", "WCT_SCOPE_MAC2", "WCT_SCOPE_MED2", "WCT_SUPP", "WCT_MUZZ1", "WCT_MUZZ2", "WCT_MUZZ3", "WCT_MUZZ4", "WCT_MUZZ5", "WCT_MUZZ6", "WCT_MUZZ7", "WCT_BARR", "WCT_BARR2", "WCT_CAMO_1", "WCT_CAMO_2", "WCT_CAMO_3", "WCT_CAMO_4", "WCT_CAMO_5", "WCT_CAMO_6", "WCT_CAMO_7", "WCT_CAMO_8", "WCT_CAMO_9", "WCT_CAMO_10", "WCT_CAMO_IND"};
const std::vector<std::string> VALUES_ATTACH_CARBINERIFLEMK2{"COMPONENT_CARBINERIFLE_MK2_CLIP_01", "COMPONENT_CARBINERIFLE_MK2_CLIP_02", "COMPONENT_CARBINERIFLE_MK2_CLIP_TRACER", "COMPONENT_CARBINERIFLE_MK2_CLIP_INCENDIARY", "COMPONENT_CARBINERIFLE_MK2_CLIP_ARMORPIERCING", "COMPONENT_CARBINERIFLE_MK2_CLIP_FMJ", "COMPONENT_AT_AR_AFGRIP_02", "COMPONENT_AT_AR_FLSH", "COMPONENT_AT_SIGHTS", "COMPONENT_AT_SCOPE_MACRO_MK2", "COMPONENT_AT_SCOPE_MEDIUM_MK2", "COMPONENT_AT_AR_SUPP", "COMPONENT_AT_MUZZLE_01", "COMPONENT_AT_MUZZLE_02", "COMPONENT_AT_MUZZLE_03", "COMPONENT_AT_MUZZLE_04", "COMPONENT_AT_MUZZLE_05", "COMPONENT_AT_MUZZLE_06", "COMPONENT_AT_MUZZLE_07", "COMPONENT_AT_CR_BARREL_01", "COMPONENT_AT_CR_BARREL_02", "COMPONENT_CARBINERIFLE_MK2_CAMO", "COMPONENT_CARBINERIFLE_MK2_CAMO_02", "COMPONENT_CARBINERIFLE_MK2_CAMO_03", "COMPONENT_CARBINERIFLE_MK2_CAMO_04", "COMPONENT_CARBINERIFLE_MK2_CAMO_05", "COMPONENT_CARBINERIFLE_MK2_CAMO_06", "COMPONENT_CARBINERIFLE_MK2_CAMO_07", "COMPONENT_CARBINERIFLE_MK2_CAMO_08", "COMPONENT_CARBINERIFLE_MK2_CAMO_09", "COMPONENT_CARBINERIFLE_MK2_CAMO_10", "COMPONENT_CARBINERIFLE_MK2_CAMO_IND_01"};

const std::vector<std::string> CAPTIONS_ATTACH_COMBATMGMK2{"WCT_CLIP1", "WCT_CLIP2", "WCT_CLIP_TR", "WCT_CLIP_INC", "WCT_CLIP_AP", "WCT_CLIP_FMJ", "WCT_GRIP", "WCT_HOLO", "WCT_SCOPE_SML2", "WCT_SCOPE_MED2", "WCT_MUZZ1", "WCT_MUZZ2", "WCT_MUZZ3", "WCT_MUZZ4", "WCT_MUZZ5", "WCT_MUZZ6", "WCT_MUZZ7", "WCT_BARR", "WCT_BARR2", "WCT_CAMO_1", "WCT_CAMO_2", "WCT_CAMO_3", "WCT_CAMO_4", "WCT_CAMO_5", "WCT_CAMO_6", "WCT_CAMO_7", "WCT_CAMO_8", "WCT_CAMO_9", "WCT_CAMO_10", "WCT_CAMO_IND"};
const std::vector<std::string> VALUES_ATTACH_COMBATMGMK2{"COMPONENT_COMBATMG_MK2_CLIP_01", "COMPONENT_COMBATMG_MK2_CLIP_02", "COMPONENT_COMBATMG_MK2_CLIP_TRACER", "COMPONENT_COMBATMG_MK2_CLIP_INCENDIARY", "COMPONENT_COMBATMG_MK2_CLIP_ARMORPIERCING", "COMPONENT_COMBATMG_MK2_CLIP_FMJ", "COMPONENT_AT_AR_AFGRIP_02", "COMPONENT_AT_SIGHTS", "COMPONENT_AT_SCOPE_SMALL_MK2", "COMPONENT_AT_SCOPE_MEDIUM_MK2", "COMPONENT_AT_MUZZLE_01", "COMPONENT_AT_MUZZLE_02", "COMPONENT_AT_MUZZLE_03", "COMPONENT_AT_MUZZLE_04", "COMPONENT_AT_MUZZLE_05", "COMPONENT_AT_MUZZLE_06", "COMPONENT_AT_MUZZLE_07", "COMPONENT_AT_MG_BARREL_01", "COMPONENT_AT_MG_BARREL_02", "COMPONENT_COMBATMG_MK2_CAMO", "COMPONENT_COMBATMG_MK2_CAMO_02", "COMPONENT_COMBATMG_MK2_CAMO_03", "COMPONENT_COMBATMG_MK2_CAMO_04", "COMPONENT_COMBATMG_MK2_CAMO_05", "COMPONENT_COMBATMG_MK2_CAMO_06", "COMPONENT_COMBATMG_MK2_CAMO_07", "COMPONENT_COMBATMG_MK2_CAMO_08", "COMPONENT_COMBATMG_MK2_CAMO_09", "COMPONENT_COMBATMG_MK2_CAMO_10", "COMPONENT_COMBATMG_MK2_CAMO_IND_01"};

const std::vector<std::string> CAPTIONS_ATTACH_HEAVYSNIPERMK2{"WCT_CLIP1", "WCT_CLIP2", "WCT_CLIP_INC", "WCT_CLIP_AP", "WCT_CLIP_FMJ", "WCT_CLIP_EX", "WCT_SCOPE_LRG2", "WCT_SCOPE_MAX", "WCT_SCOPE_NV", "WCT_SCOPE_TH", "WCT_SUPP", "WCT_MUZZ8", "WCT_MUZZ9", "WCT_BARR", "WCT_BARR2", "WCT_CAMO_1", "WCT_CAMO_2", "WCT_CAMO_3", "WCT_CAMO_4", "WCT_CAMO_5", "WCT_CAMO_6", "WCT_CAMO_7", "WCT_CAMO_8", "WCT_CAMO_9", "WCT_CAMO_10", "WCT_CAMO_IND"};
const std::vector<std::string> VALUES_ATTACH_HEAVYSNIPERMK2{"COMPONENT_HEAVYSNIPER_MK2_CLIP_01", "COMPONENT_HEAVYSNIPER_MK2_CLIP_02", "COMPONENT_HEAVYSNIPER_MK2_CLIP_INCENDIARY", "COMPONENT_HEAVYSNIPER_MK2_CLIP_ARMORPIERCING", "COMPONENT_HEAVYSNIPER_MK2_CLIP_FMJ", "COMPONENT_HEAVYSNIPER_MK2_CLIP_EXPLOSIVE", "COMPONENT_AT_SCOPE_LARGE_MK2", "COMPONENT_AT_SCOPE_MAX", "COMPONENT_AT_SCOPE_NV", "COMPONENT_AT_SCOPE_THERMAL", "COMPONENT_AT_SR_SUPP_03", "COMPONENT_AT_MUZZLE_08", "COMPONENT_AT_MUZZLE_09", "COMPONENT_AT_SR_BARREL_01", "COMPONENT_AT_SR_BARREL_02", "COMPONENT_HEAVYSNIPER_MK2_CAMO", "COMPONENT_HEAVYSNIPER_MK2_CAMO_02", "COMPONENT_HEAVYSNIPER_MK2_CAMO_03", "COMPONENT_HEAVYSNIPER_MK2_CAMO_04", "COMPONENT_HEAVYSNIPER_MK2_CAMO_05", "COMPONENT_HEAVYSNIPER_MK2_CAMO_06", "COMPONENT_HEAVYSNIPER_MK2_CAMO_07", "COMPONENT_HEAVYSNIPER_MK2_CAMO_08", "COMPONENT_HEAVYSNIPER_MK2_CAMO_09", "COMPONENT_HEAVYSNIPER_MK2_CAMO_10", "COMPONENT_HEAVYSNIPER_MK2_CAMO_IND_01"};

/*Doomsday Heist*/
const std::vector<std::string> CAPTIONS_ATTACH_SNSPISTOLMK2{"WCT_CLIP1", "WCT_CLIP2", "WCT_CLIP_TR", "WCT_CLIP_INC", "WCT_CLIP_HP", "WCT_CLIP_FMJ", "WCT_FLASH", "WCT_SCOPE_PI", "WCT_SUPP", "WCT_COMP", "WCT_CAMO_1", "WCT_CAMO_2", "WCT_CAMO_3", "WCT_CAMO_4", "WCT_CAMO_5", "WCT_CAMO_6", "WCT_CAMO_7", "WCT_CAMO_8", "WCT_CAMO_9", "WCT_CAMO_10", "WCT_CAMO_IND", "WCT_CAMO_1", "WCT_CAMO_2", "WCT_CAMO_3", "WCT_CAMO_4", "WCT_CAMO_5", "WCT_CAMO_6", "WCT_CAMO_7", "WCT_CAMO_8", "WCT_CAMO_9", "WCT_CAMO_10", "WCT_CAMO_IND" };
const std::vector<std::string> VALUES_ATTACH_SNSPISTOLMK2{"COMPONENT_SNSPISTOL_MK2_CLIP_01", "COMPONENT_SNSPISTOL_MK2_CLIP_02", "COMPONENT_SNSPISTOL_MK2_CLIP_TRACER", "COMPONENT_SNSPISTOL_MK2_CLIP_INCENDIARY", "COMPONENT_SNSPISTOL_MK2_CLIP_HOLLOWPOINT", "COMPONENT_SNSPISTOL_MK2_CLIP_FMJ", "COMPONENT_AT_PI_FLSH_03", "COMPONENT_AT_PI_RAIL_02", "COMPONENT_AT_PI_SUPP_02", "COMPONENT_AT_PI_COMP_02", "COMPONENT_SNSPISTOL_MK2_CAMO", "COMPONENT_SNSPISTOL_MK2_CAMO_02", "COMPONENT_SNSPISTOL_MK2_CAMO_03", "COMPONENT_SNSPISTOL_MK2_CAMO_04", "COMPONENT_SNSPISTOL_MK2_CAMO_05", "COMPONENT_SNSPISTOL_MK2_CAMO_06", "COMPONENT_SNSPISTOL_MK2_CAMO_07", "COMPONENT_SNSPISTOL_MK2_CAMO_08", "COMPONENT_SNSPISTOL_MK2_CAMO_09", "COMPONENT_SNSPISTOL_MK2_CAMO_10", "COMPONENT_SNSPISTOL_MK2_CAMO_IND_01", "COMPONENT_SNSPISTOL_MK2_CAMO_SLIDE", "COMPONENT_SNSPISTOL_MK2_CAMO_02_SLIDE", "COMPONENT_SNSPISTOL_MK2_CAMO_03_SLIDE", "COMPONENT_SNSPISTOL_MK2_CAMO_04_SLIDE", "COMPONENT_SNSPISTOL_MK2_CAMO_05_SLIDE", "COMPONENT_SNSPISTOL_MK2_CAMO_06_SLIDE", "COMPONENT_SNSPISTOL_MK2_CAMO_07_SLIDE", "COMPONENT_SNSPISTOL_MK2_CAMO_08_SLIDE", "COMPONENT_SNSPISTOL_MK2_CAMO_09_SLIDE", "COMPONENT_SNSPISTOL_MK2_CAMO_10_SLIDE", "COMPONENT_SNSPISTOL_MK2_CAMO_IND_01_SLIDE"};

const std::vector<std::string> CAPTIONS_ATTACH_REVOLVERMK2{"WCT_CLIP1_RV", "WCT_CLIP_TR", "WCT_CLIP_INC", "WCT_CLIP_HP", "WCT_CLIP_FMJ", "WCT_HOLO", "WCT_SCOPE_MAC2", "WCT_FLASH", "WCT_COMP", "WCT_CAMO_1", "WCT_CAMO_2", "WCT_CAMO_3", "WCT_CAMO_4", "WCT_CAMO_5", "WCT_CAMO_6", "WCT_CAMO_7", "WCT_CAMO_8", "WCT_CAMO_9", "WCT_CAMO_10", "WCT_CAMO_IND"};
const std::vector<std::string> VALUES_ATTACH_REVOLVERMK2{"COMPONENT_REVOLVER_MK2_CLIP_01", "COMPONENT_REVOLVER_MK2_CLIP_TRACER", "COMPONENT_REVOLVER_MK2_CLIP_INCENDIARY", "COMPONENT_REVOLVER_MK2_CLIP_HOLLOWPOINT", "COMPONENT_REVOLVER_MK2_CLIP_FMJ", "COMPONENT_AT_SIGHTS", "COMPONENT_AT_SCOPE_MACRO_MK2", "COMPONENT_AT_PI_FLSH", "COMPONENT_AT_PI_COMP_03", "COMPONENT_REVOLVER_MK2_CAMO", "COMPONENT_REVOLVER_MK2_CAMO_02", "COMPONENT_REVOLVER_MK2_CAMO_03", "COMPONENT_REVOLVER_MK2_CAMO_04", "COMPONENT_REVOLVER_MK2_CAMO_05", "COMPONENT_REVOLVER_MK2_CAMO_06", "COMPONENT_REVOLVER_MK2_CAMO_07", "COMPONENT_REVOLVER_MK2_CAMO_08", "COMPONENT_REVOLVER_MK2_CAMO_09", "COMPONENT_REVOLVER_MK2_CAMO_10", "COMPONENT_REVOLVER_MK2_CAMO_IND_01"};

const std::vector<std::string> CAPTIONS_ATTACH_SPECIALCARBINEMK2{"WCT_CLIP1", "WCT_CLIP2", "WCT_CLIP_TR", "WCT_CLIP_INC", "WCT_CLIP_AP", "WCT_CLIP_FMJ", "WCT_FLASH", "WCT_HOLO", "WCT_SCOPE_MAC2", "WCT_SCOPE_MED2", "WCT_SUPP", "WCT_MUZZ1", "WCT_MUZZ2", "WCT_MUZZ3", "WCT_MUZZ4", "WCT_MUZZ5", "WCT_MUZZ6", "WCT_MUZZ7", "WCT_GRIP", "WCT_BARR", "WCT_BARR2", "WCT_CAMO_1", "WCT_CAMO_2", "WCT_CAMO_3", "WCT_CAMO_4", "WCT_CAMO_5", "WCT_CAMO_6", "WCT_CAMO_7", "WCT_CAMO_8", "WCT_CAMO_9", "WCT_CAMO_10", "WCT_CAMO_IND"};
const std::vector<std::string> VALUES_ATTACH_SPECIALCARBINEMK2{"COMPONENT_SPECIALCARBINE_MK2_CLIP_01", "COMPONENT_SPECIALCARBINE_MK2_CLIP_02", "COMPONENT_SPECIALCARBINE_MK2_CLIP_TRACER", "COMPONENT_SPECIALCARBINE_MK2_CLIP_INCENDIARY", "COMPONENT_SPECIALCARBINE_MK2_CLIP_ARMORPIERCING", "COMPONENT_SPECIALCARBINE_MK2_CLIP_FMJ", "COMPONENT_AT_AR_FLSH", "COMPONENT_AT_SIGHTS", "COMPONENT_AT_SCOPE_MACRO_MK2", "COMPONENT_AT_SCOPE_MEDIUM_MK2", "COMPONENT_AT_AR_SUPP_02", "COMPONENT_AT_MUZZLE_01", "COMPONENT_AT_MUZZLE_02", "COMPONENT_AT_MUZZLE_03", "COMPONENT_AT_MUZZLE_04", "COMPONENT_AT_MUZZLE_05", "COMPONENT_AT_MUZZLE_06", "COMPONENT_AT_MUZZLE_07", "COMPONENT_AT_AR_AFGRIP_02", "COMPONENT_AT_SC_BARREL_01", "COMPONENT_AT_SC_BARREL_02", "COMPONENT_SPECIALCARBINE_MK2_CAMO", "COMPONENT_SPECIALCARBINE_MK2_CAMO_02", "COMPONENT_SPECIALCARBINE_MK2_CAMO_03", "COMPONENT_SPECIALCARBINE_MK2_CAMO_04", "COMPONENT_SPECIALCARBINE_MK2_CAMO_05", "COMPONENT_SPECIALCARBINE_MK2_CAMO_06", "COMPONENT_SPECIALCARBINE_MK2_CAMO_07", "COMPONENT_SPECIALCARBINE_MK2_CAMO_08", "COMPONENT_SPECIALCARBINE_MK2_CAMO_09", "COMPONENT_SPECIALCARBINE_MK2_CAMO_10", "COMPONENT_SPECIALCARBINE_MK2_CAMO_IND_01"};

const std::vector<std::string> CAPTIONS_ATTACH_BULLPUPMK2{"WCT_CLIP1", "WCT_CLIP2", "WCT_CLIP_TR", "WCT_CLIP_INC", "WCT_CLIP_AP", "WCT_CLIP_FMJ", "WCT_FLASH", "WCT_HOLO", "WCT_SCOPE_MAC2", "WCT_SCOPE_SML2", "WCT_BARR", "WCT_BARR2", "WCT_SUPP", "WCT_MUZZ1", "WCT_MUZZ2", "WCT_MUZZ3", "WCT_MUZZ4", "WCT_MUZZ5", "WCT_MUZZ6", "WCT_MUZZ7", "WCT_GRIP", "WCT_CAMO_1", "WCT_CAMO_2", "WCT_CAMO_3", "WCT_CAMO_4", "WCT_CAMO_5", "WCT_CAMO_6", "WCT_CAMO_7", "WCT_CAMO_8", "WCT_CAMO_9", "WCT_CAMO_10", "WCT_CAMO_IND"};
const std::vector<std::string> VALUES_ATTACH_BULLPUPMK2{"COMPONENT_BULLPUPRIFLE_MK2_CLIP_01", "COMPONENT_BULLPUPRIFLE_MK2_CLIP_02", "COMPONENT_BULLPUPRIFLE_MK2_CLIP_TRACER", "COMPONENT_BULLPUPRIFLE_MK2_CLIP_INCENDIARY", "COMPONENT_BULLPUPRIFLE_MK2_CLIP_ARMORPIERCING", "COMPONENT_BULLPUPRIFLE_MK2_CLIP_FMJ", "COMPONENT_AT_AR_FLSH", "COMPONENT_AT_SIGHTS", "COMPONENT_AT_SCOPE_MACRO_02_MK2", "COMPONENT_AT_SCOPE_SMALL_MK2", "COMPONENT_AT_BP_BARREL_01", "COMPONENT_AT_BP_BARREL_02", "COMPONENT_AT_AR_SUPP", "COMPONENT_AT_MUZZLE_01", "COMPONENT_AT_MUZZLE_02", "COMPONENT_AT_MUZZLE_03", "COMPONENT_AT_MUZZLE_04","COMPONENT_AT_MUZZLE_05","COMPONENT_AT_MUZZLE_06","COMPONENT_AT_MUZZLE_07","COMPONENT_AT_AR_AFGRIP_02","COMPONENT_BULLPUPRIFLE_MK2_CAMO","COMPONENT_BULLPUPRIFLE_MK2_CAMO_02","COMPONENT_BULLPUPRIFLE_MK2_CAMO_03","COMPONENT_BULLPUPRIFLE_MK2_CAMO_04","COMPONENT_BULLPUPRIFLE_MK2_CAMO_05", "COMPONENT_BULLPUPRIFLE_MK2_CAMO_06", "COMPONENT_BULLPUPRIFLE_MK2_CAMO_07", "COMPONENT_BULLPUPRIFLE_MK2_CAMO_08", "COMPONENT_BULLPUPRIFLE_MK2_CAMO_09", "COMPONENT_BULLPUPRIFLE_MK2_CAMO_10", "COMPONENT_BULLPUPRIFLE_MK2_CAMO_IND_01"};

const std::vector<std::string> CAPTIONS_ATTACH_PUMPSHOTGUNMK2{"WCT_SHELL", "WCT_SHELL_INC", "WCT_SHELL_AP", "WCT_SHELL_HP", "WCT_SHELL_EX", "WCT_HOLO", "WCT_SCOPE_MAC2", "WCT_SCOPE_SML2", "WCT_FLASH", "WCT_SUPP", "WCT_MUZZ", "WCT_CAMO_1", "WCT_CAMO_2", "WCT_CAMO_3", "WCT_CAMO_4", "WCT_CAMO_5", "WCT_CAMO_6", "WCT_CAMO_7", "WCT_CAMO_8", "WCT_CAMO_9", "WCT_CAMO_10", "WCT_CAMO_IND"};
const std::vector<std::string> VALUES_ATTACH_PUMPSHOTGUNMK2{"COMPONENT_PUMPSHOTGUN_MK2_CLIP_01", "COMPONENT_PUMPSHOTGUN_MK2_CLIP_INCENDIARY", "COMPONENT_PUMPSHOTGUN_MK2_CLIP_ARMORPIERCING", "COMPONENT_PUMPSHOTGUN_MK2_CLIP_HOLLOWPOINT", "COMPONENT_PUMPSHOTGUN_MK2_CLIP_EXPLOSIVE", "COMPONENT_AT_SIGHTS", "COMPONENT_AT_SCOPE_MACRO_MK2", "COMPONENT_AT_SCOPE_SMALL_MK2", "COMPONENT_AT_AR_FLSH", "COMPONENT_AT_SR_SUPP_03", "COMPONENT_AT_MUZZLE_08", "COMPONENT_PUMPSHOTGUN_MK2_CAMO", "COMPONENT_PUMPSHOTGUN_MK2_CAMO_02", "COMPONENT_PUMPSHOTGUN_MK2_CAMO_03", "COMPONENT_PUMPSHOTGUN_MK2_CAMO_04", "COMPONENT_PUMPSHOTGUN_MK2_CAMO_05", "COMPONENT_PUMPSHOTGUN_MK2_CAMO_06", "COMPONENT_PUMPSHOTGUN_MK2_CAMO_07", "COMPONENT_PUMPSHOTGUN_MK2_CAMO_08", "COMPONENT_PUMPSHOTGUN_MK2_CAMO_09", "COMPONENT_PUMPSHOTGUN_MK2_CAMO_10", "COMPONENT_PUMPSHOTGUN_MK2_CAMO_IND_01"};

const std::vector<std::string> CAPTIONS_ATTACH_MARKSMANRIFLEMK2{"WCT_CLIP1", "WCT_CLIP2", "WCT_CLIP_TR", "WCT_CLIP_INC", "WCT_CLIP_AP", "WCT_CLIP_FMJ", "WCT_HOLO", "WCT_SCOPE_MED2", "WCT_SCOPE_LRG2", "WCT_FLASH", "WCT_SUPP", "WCT_MUZZ1", "WCT_MUZZ2", "WCT_MUZZ3", "WCT_MUZZ4", "WCT_MUZZ5", "WCT_MUZZ6", "WCT_MUZZ7", "WCT_BARR", "WCT_BARR2", "WCT_GRIP", "WCT_CAMO_1", "WCT_CAMO_2", "WCT_CAMO_3", "WCT_CAMO_4", "WCT_CAMO_5", "WCT_CAMO_6", "WCT_CAMO_7", "WCT_CAMO_8", "WCT_CAMO_9", "WCT_CAMO_10", "WCT_CAMO_IND"};
const std::vector<std::string> VALUES_ATTACH_MARKSMANRIFLEMK2{"COMPONENT_MARKSMANRIFLE_MK2_CLIP_01", "COMPONENT_MARKSMANRIFLE_MK2_CLIP_02", "COMPONENT_MARKSMANRIFLE_MK2_CLIP_TRACER", "COMPONENT_MARKSMANRIFLE_MK2_CLIP_INCENDIARY", "COMPONENT_MARKSMANRIFLE_MK2_CLIP_ARMORPIERCING", "COMPONENT_MARKSMANRIFLE_MK2_CLIP_FMJ", "COMPONENT_AT_SIGHTS", "COMPONENT_AT_SCOPE_MEDIUM_MK2", "COMPONENT_AT_SCOPE_LARGE_FIXED_ZOOM_MK2", "COMPONENT_AT_AR_FLSH", "COMPONENT_AT_AR_SUPP", "COMPONENT_AT_MUZZLE_01", "COMPONENT_AT_MUZZLE_02", "COMPONENT_AT_MUZZLE_03", "COMPONENT_AT_MUZZLE_04", "COMPONENT_AT_MUZZLE_05", "COMPONENT_AT_MUZZLE_06", "COMPONENT_AT_MUZZLE_07", "COMPONENT_AT_MRFL_BARREL_01", "COMPONENT_AT_MRFL_BARREL_02", "COMPONENT_AT_AR_AFGRIP_02", "COMPONENT_MARKSMANRIFLE_MK2_CAMO", "COMPONENT_MARKSMANRIFLE_MK2_CAMO_02", "COMPONENT_MARKSMANRIFLE_MK2_CAMO_03", "COMPONENT_MARKSMANRIFLE_MK2_CAMO_04", "COMPONENT_MARKSMANRIFLE_MK2_CAMO_05", "COMPONENT_MARKSMANRIFLE_MK2_CAMO_06", "COMPONENT_MARKSMANRIFLE_MK2_CAMO_07", "COMPONENT_MARKSMANRIFLE_MK2_CAMO_08", "COMPONENT_MARKSMANRIFLE_MK2_CAMO_09", "COMPONENT_MARKSMANRIFLE_MK2_CAMO_10", "COMPONENT_MARKSMANRIFLE_MK2_CAMO_IND_01"};

//Ray Pistol
const std::vector<std::string> CAPTIONS_ATTACH_RAY_PISTOL{"WCT_VAR_RAY18"};
const std::vector<std::string> VALUES_ATTACH_RAY_PISTOL{"COMPONENT_RAYPISTOL_VARMOD_XMAS18"};

//Tintable weapons list
const std::vector<std::string> WEAPONTYPES_TINT{ "WEAPON_PISTOL", "WEAPON_COMBATPISTOL", "WEAPON_APPISTOL", "WEAPON_PISTOL50", "WEAPON_SNSPISTOL", "WEAPON_HEAVYPISTOL", "WEAPON_VINTAGEPISTOL", "WEAPON_STUNGUN", "WEAPON_FLAREGUN", "WEAPON_MARKSMANPISTOL", "WEAPON_MICROSMG", "WEAPON_SMG", "WEAPON_ASSAULTSMG", "WEAPON_MG", "WEAPON_COMBATMG", "WEAPON_GUSENBERG", "WEAPON_ASSAULTRIFLE", "WEAPON_CARBINERIFLE", "WEAPON_ADVANCEDRIFLE", "WEAPON_SPECIALCARBINE", "WEAPON_BULLPUPRIFLE", "WEAPON_PUMPSHOTGUN", "WEAPON_SAWNOFFSHOTGUN", "WEAPON_BULLPUPSHOTGUN", "WEAPON_ASSAULTSHOTGUN", "WEAPON_MUSKET", "WEAPON_HEAVYSHOTGUN", "WEAPON_SNIPERRIFLE", "WEAPON_HEAVYSNIPER", "WEAPON_MARKSMANRIFLE", "WEAPON_GRENADELAUNCHER", "WEAPON_RPG", "WEAPON_MINIGUN", "WEAPON_FIREWORK", "WEAPON_RAILGUN", "WEAPON_HOMINGLAUNCHER", "WEAPON_COMBATPDW", "WEAPON_MACHINEPISTOL", "WEAPON_DBSHOTGUN", "WEAPON_COMPACTRIFLE", "WEAPON_AUTOSHOTGUN", "WEAPON_COMPACTLAUNCHER", "WEAPON_MINISMG", "WEAPON_PISTOL_MK2", "WEAPON_SMG_MK2", "WEAPON_ASSAULTRIFLE_MK2", "WEAPON_CARBINERIFLE_MK2", "WEAPON_COMBATMG_MK2", "WEAPON_HEAVYSNIPER_MK2", /*"WEAPON_SNSPISTOL_MK2", "WEAPON_REVOLVER_MK2", "WEAPON_SPECIALCARBINE_MK2", "WEAPON_BULLPUPRIFLE_MK2", "WEAPON_PUMPSHOTGUN_MK2", "WEAPON_MARKSMANRIFLE_MK2", WEAPON_DOUBLEACTION*/ "WEAPON_RAYPISTOL", "WEAPON_RAYCARBINE", "WEAPON_RAYMINIGUN" };

//moddable weapons list
const std::vector<std::string> WEAPONTYPES_MOD{ "WEAPON_PISTOL", "WEAPON_HEAVYPISTOL", "WEAPON_COMBATPISTOL", "WEAPON_APPISTOL", "WEAPON_PISTOL50", "WEAPON_MICROSMG", "WEAPON_SMG", "WEAPON_ASSAULTSMG", "WEAPON_ASSAULTRIFLE", "WEAPON_CARBINERIFLE", "WEAPON_ADVANCEDRIFLE", "WEAPON_MG", "WEAPON_COMBATMG", "WEAPON_SAWNOFFSHOTGUN", "WEAPON_PUMPSHOTGUN", "WEAPON_ASSAULTSHOTGUN", "WEAPON_BULLPUPSHOTGUN", "WEAPON_SNIPERRIFLE", "WEAPON_HEAVYSNIPER", "WEAPON_GRENADELAUNCHER", "WEAPON_BULLPUPRIFLE", "WEAPON_GUSENBERG", "WEAPON_HEAVYSHOTGUN", "WEAPON_MARKSMANRIFLE", "WEAPON_SNSPISTOL", "WEAPON_SPECIALCARBINE", "WEAPON_VINTAGEPISTOL", "WEAPON_COMBATPDW", "WEAPON_MACHINEPISTOL", "WEAPON_SWITCHBLADE", "WEAPON_REVOLVER", "WEAPON_COMPACTRIFLE", "WEAPON_MINISMG", "WEAPON_PISTOL_MK2", "WEAPON_SMG_MK2", "WEAPON_ASSAULTRIFLE_MK2", "WEAPON_CARBINERIFLE_MK2", "WEAPON_COMBATMG_MK2", "WEAPON_HEAVYSNIPER_MK2", "WEAPON_SNSPISTOL_MK2", "WEAPON_REVOLVER_MK2", "WEAPON_SPECIALCARBINE_MK2", "WEAPON_BULLPUPRIFLE_MK2", "WEAPON_PUMPSHOTGUN_MK2", "WEAPON_MARKSMANRIFLE_MK2" };

const std::vector<std::string> VOV_WEAPONMOD_CAPTIONS[] = { CAPTIONS_ATTACH_PISTOL, CAPTIONS_ATTACH_HEAVYPISTOL, CAPTIONS_ATTACH_COMBATPISTOL, CAPTIONS_ATTACH_APPISTOL, CAPTIONS_ATTACH_PISTOL50, CAPTIONS_ATTACH_MICROSMG, CAPTIONS_ATTACH_SMG, CAPTIONS_ATTACH_ASSAULTSMG, CAPTIONS_ATTACH_ASSAULTRIFLE, CAPTIONS_ATTACH_CARBINERIFLE, CAPTIONS_ATTACH_ADVANCEDRIFLE, CAPTIONS_ATTACH_MG, CAPTIONS_ATTACH_COMBATMG, CAPTIONS_ATTACH_SAWNOFF, CAPTIONS_ATTACH_PUMPSHOTGUN, CAPTIONS_ATTACH_ASSAULTSHOTGUN, CAPTIONS_ATTACH_BULLPUPSHOTGUN, CAPTIONS_ATTACH_SNIPERRIFLE, CAPTIONS_ATTACH_HEAVYSNIPER, CAPTIONS_ATTACH_GRENADELAUNCHER, CAPTIONS_ATTACH_BULLPUPRIFLE, CAPTIONS_ATTACH_GUSENBERG, CAPTIONS_ATTACH_HEAVYSHOTGUN, CAPTIONS_ATTACH_MARKSMANRIFLE, CAPTIONS_ATTACH_SNSPISTOL, CAPTIONS_ATTACH_SPECIALCARBINE, CAPTIONS_ATTACH_VINTAGEPISTOL, CAPTIONS_ATTACH_COMBATPDW, CAPTIONS_ATTACH_MACHINEPISTOL, CAPTIONS_ATTACH_SWITCHBLADE, CAPTIONS_ATTACH_REVOLVER, CAPTIONS_ATTACH_COMPACTRIFLE, CAPTIONS_ATTACH_MINISMG, CAPTIONS_ATTACH_PISTOLMK2, CAPTIONS_ATTACH_SMGMK2, CAPTIONS_ATTACH_ASSAULTRIFLEMK2, CAPTIONS_ATTACH_CARBINERIFLEMK2, CAPTIONS_ATTACH_COMBATMGMK2, CAPTIONS_ATTACH_HEAVYSNIPERMK2, CAPTIONS_ATTACH_SNSPISTOLMK2, CAPTIONS_ATTACH_REVOLVERMK2, CAPTIONS_ATTACH_SPECIALCARBINEMK2, CAPTIONS_ATTACH_BULLPUPMK2, CAPTIONS_ATTACH_PUMPSHOTGUNMK2, CAPTIONS_ATTACH_MARKSMANRIFLEMK2, CAPTIONS_ATTACH_RAY_PISTOL, CAPTIONS_ATTACH_CERAMIC_PISTOL };
const std::vector<std::string> VOV_WEAPONMOD_VALUES[] = { VALUES_ATTACH_PISTOL, VALUES_ATTACH_HEAVYPISTOL, VALUES_ATTACH_COMBATPISTOL, VALUES_ATTACH_APPISTOL, VALUES_ATTACH_PISTOL50, VALUES_ATTACH_MICROSMG, VALUES_ATTACH_SMG, VALUES_ATTACH_ASSAULTSMG, VALUES_ATTACH_ASSAULTRIFLE, VALUES_ATTACH_CARBINERIFLE, VALUES_ATTACH_ADVANCEDRIFLE, VALUES_ATTACH_MG, VALUES_ATTACH_COMBATMG, VALUES_ATTACH_SAWNOFF, VALUES_ATTACH_PUMPSHOTGUN, VALUES_ATTACH_ASSAULTSHOTGUN, VALUES_ATTACH_BULLPUPSHOTGUN, VALUES_ATTACH_SNIPERRIFLE, VALUES_ATTACH_HEAVYSNIPER, VALUES_ATTACH_GRENADELAUNCHER, VALUES_ATTACH_BULLPUPRIFLE, VALUES_ATTACH_GUSENBERG, VALUES_ATTACH_HEAVYSHOTGUN, VALUES_ATTACH_MARKSMANRIFLE, VALUES_ATTACH_SNSPISTOL, VALUES_ATTACH_SPECIALCARBINE, VALUES_ATTACH_VINTAGEPISTOL, VALUES_ATTACH_COMBATPDW, VALUES_ATTACH_MACHINEPISTOL, VALUES_ATTACH_SWITCHBLADE, VALUES_ATTACH_REVOLVER, VALUES_ATTACH_COMPACTRIFLE, VALUES_ATTACH_MINISMG, VALUES_ATTACH_PISTOLMK2, VALUES_ATTACH_SMGMK2, VALUES_ATTACH_ASSAULTRIFLEMK2, VALUES_ATTACH_CARBINERIFLEMK2, VALUES_ATTACH_COMBATMGMK2, VALUES_ATTACH_HEAVYSNIPERMK2, VALUES_ATTACH_SNSPISTOLMK2, VALUES_ATTACH_REVOLVERMK2, VALUES_ATTACH_SPECIALCARBINEMK2, VALUES_ATTACH_BULLPUPMK2, VALUES_ATTACH_PUMPSHOTGUNMK2, VALUES_ATTACH_MARKSMANRIFLEMK2, VALUES_ATTACH_RAY_PISTOL, VALUES_ATTACH_CERAMIC_PISTOL };

//MK2 weapons 
const std::vector<char*> MK2_WEAPONS{"WEAPON_PISTOL_MK2", "WEAPON_SNSPISTOL_MK2", "WEAPON_REVOLVER_MK2", "WEAPON_SMG_MK2", "WEAPON_COMBATMG_MK2", "WEAPON_ASSAULTRIFLE_MK2", "WEAPON_BULLPUPRIFLE_MK2", "WEAPON_CARBINERIFLE_MK2", "WEAPON_SPECIALCARBINE_MK2", "WEAPON_PUMPSHOTGUN_MK2", "WEAPON_HEAVYSNIPER_MK2", "WEAPON_MARKSMANRIFLE_MK2"};
const std::vector<char*> MK2_WEAPONS_LIVERY_COMP{"COMPONENT_PISTOL_MK2_CAMO", "COMPONENT_SNSPISTOL_MK2_CAMO", "COMPONENT_REVOLVER_MK2_CAMO", "COMPONENT_SMG_MK2_CAMO", "COMPONENT_COMBATMG_MK2_CAMO", "COMPONENT_ASSAULTRIFLE_MK2_CAMO", "COMPONENT_BULLPUPRIFLE_MK2_CAMO", "COMPONENT_CARBINERIFLE_MK2_CAMO", "COMPONENT_SPECIALCARBINE_MK2_CAMO", "COMPONENT_PUMPSHOTGUN_MK2_CAMO", "COMPONENT_HEAVYSNIPER_MK2_CAMO", "COMPONENT_MARKSMANRIFLE_MK2_CAMO" };

//Weapon damage modifier list
const std::vector<std::string> WEAP_DMG_CAPTIONS{"1.0x", "1.5x", "2.0x", "3.0x", "5.0x", "10.0x", "50.0x", "100.0x", "1000.0x"};
const std::vector<float> WEAP_DMG_FLOAT{1.0, 1.5, 2.0, 3.0, 5.0, 10.0, 50.0, 100.0, 1000.0};

const int PARACHUTE_ID = 0xFBAB5776;

const int TOTAL_WEAPONS_COUNT = 86;
//const int TOTAL_WEAPONS_SLOTS = 81;
const int MAX_MOD_SLOTS = 15; 

extern bool featureNightVision;
extern bool featureThermalVision;
extern int activeLineIndexPowerPunchWeapons;
extern const std::vector<std::string> WEAPONS_POWERPUNCH_CAPTIONS;
extern const int WEAPONS_POWERPUNCH_VALUES[];
extern int PowerPunchIndex;
extern bool PowerPunchChanged;
extern bool featurePunchFists;
extern bool featurePunchMeleeWeapons;
extern bool featurePunchFireWeapons;
extern bool featurePowerPunch;
extern std::string lastPowerWeapon;

extern int tick_allw;

bool process_weapon_menu();

bool process_weaponlist_menu();

void reset_weapon_globals();

void update_weapon_features(BOOL bPlayerExists, Player player);

void onchange_cop_armed_index(int value, SelectFromListMenuItem* source);

void onchange_chance_police_calling_index(int value, SelectFromListMenuItem* source);

void onchange_chance_attacking_you_index(int value, SelectFromListMenuItem* source);

void onchange_power_punch_index(int value, SelectFromListMenuItem* source);

void onchange_weapons_firemode_modifier(int value, SelectFromListMenuItem* source);

void onchange_sniper_vision_modifier(int value, SelectFromListMenuItem* source);

void onchange_vehicle_weapon_modifier(int value, SelectFromListMenuItem* source);

void onchange_weapon_no_reticle_modifier(int value, SelectFromListMenuItem* source);

void onchange_weapon_load_saved_modifier(int value, SelectFromListMenuItem* source);

void onchange_cop_alarm_index(int value, SelectFromListMenuItem* source);

void add_weapon_feature_enablements2(std::vector<StringPairSettingDBRow>* results);

void save_player_weapons(Ped playerPed);

void give_all_weapons_hotkey();

void sniper_vision_toggle();

void restore_player_weapons(Ped playerPed);

bool is_weapon_equipped(std::vector<int> extras);

bool process_weapon_save_slot_menu(int slot);

void set_weapon_equipped(bool equipped, std::vector<int> extras);

bool is_weaponmod_equipped(std::vector<int> extras);

void set_weaponmod_equipped(bool equipped, std::vector<int> extras);

void give_weapon_clip(MenuItem<int> choice);

void fill_weapon_ammo(MenuItem<int> choice);

void onconfirm_open_tint_menu(MenuItem<int> choice);

Vector3 DirectionOffsetFromCam(float distance);

void VectorToFloat(Vector3 unk, float *Out);

Vector3 add(Vector3* vectorA, Vector3* vectorB);

//Weapon mod menu
bool onconfirm_weapon_mod_menu_tint(MenuItem<int> choice);

void add_weapon_feature_enablements(std::vector<FeatureEnabledLocalDefinition>* results);

bool weapon_reequip_interrupt();

void onhighlight_weapon_mod_menu_tint_colour(MenuItem<int> choice);

bool onconfirm_weapon_mod_menu_tint_colour(MenuItem<int> choice);

void onconfirm_open_tint_menu_colour(MenuItem<int> choice);

// weapon damage modifier
void onchange_weap_dmg_modifier(int value, SelectFromListMenuItem* source);

void add_weapons_generic_settings(std::vector<StringPairSettingDBRow>* results);

void handle_generic_settings_weapons(std::vector<StringPairSettingDBRow>* settings);

void fire_mode_hotkey();
